tektoncd/experimental

knative-eventing-extension/OWNERS
knative-eventing-extension/README.md

see https://github.com/tektoncd/community/issues/10

Initial commit to create knative-eventing-extension

---

.github/issue-template.md
.github/pull_request_template.md
CONTRIBUTING.md
DEVELOPMENT.md
README.md
code-of-conduct.md

Add basic docs as specified at https://github.com/tektoncd/community/blob/master/process.md#project-requirements.
Note that a lot of the specifics about contributing and development
hinge on us fleshing out support for experimental projects, something
partially captured in https://github.com/tektoncd/plumbing/issues/3.

Add basic docs 📝

---

tekton-listener/OWNERS
tekton-listener/README.md

This directory will contain code for the tekton listener / event binding
proposal.
Fixes https://github.com/tektoncd/community/issues/18
review them:
- [somewhat 😅] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [mostly 😅] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Add tektonlistener / eventbinding experiment repo

---

webhooks-extension/endpoints/webhook_test.go

Tighten up testGetAllWebhooks
review them:

Compare arrays properly

---

webhooks-extension/Gopkg.lock
webhooks-extension/cmd/extension/main.go
webhooks-extension/cmd/sink/main.go
webhooks-extension/endpoints/health.go
webhooks-extension/endpoints/sink.go
webhooks-extension/endpoints/types.go
webhooks-extension/endpoints/webhook.go
webhooks-extension/pkg/logging/log.go

Use a logger that gives us more granularity than `log` such as `Infof`, `Debugf`, `Errorf` as well as `Fatalf`.
review them:
N/A
__Not to be merged please until @dibbles' incoming change is in - we've had some fun with merges!__

Use zap as logger for webhook extension

---

webhooks-extension/README.md
webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/sink-kservice.yaml
webhooks-extension/development_install.sh

This PR is for the __webhooks-extension__ directory. It allows the user to install the webhooks-extension with `ko apply -f config/`. This is a lot faster than running the `development_install.sh` script; however, the script is still a viable option for those who do not wish to use `ko`.
review them:

Install with ko

---

webhooks-extension/test/README.md
webhooks-extension/test/cleanup.sh
webhooks-extension/test/config.sh
webhooks-extension/test/install_dashboard_and_extension.sh
webhooks-extension/test/install_prereqs.sh
webhooks-extension/test/util.sh

See test/README.md for details. This sets everything up ready for testing. Actual tests to follow in subsequent PRs. 
review them:

Install Tekton dashboard, webhook-extension and prereqs

---

webhooks-extension/test/.gitignore
webhooks-extension/test/README.md
webhooks-extension/test/cleanup.sh
webhooks-extension/test/config.sh
webhooks-extension/test/credentials.sh
webhooks-extension/test/dashboard-service.yaml
webhooks-extension/test/setup_webhook_simple_test.sh
webhooks-extension/test/util.sh

Scripting and documentation for an end-to-end test of webhooks support. 
review them:

Fully scripted webhooks test

---

tekton-listener/README.md
tekton-listener/cmd/tekton-listener/main.go
tekton-listener/config/050-namespace.yaml
tekton-listener/config/100-clusterroles.yaml
tekton-listener/config/100-eventbinding.yaml
tekton-listener/config/100-serviceaccount.yaml
tekton-listener/config/200-tektonlistener.yaml
tekton-listener/config/config-logging.yaml
tekton-listener/config/controller.yaml
tekton-listener/hack/samples/eventbinding.yaml
tekton-listener/hack/samples/listener.yaml
tekton-listener/pkg/apis/pipelineexperimental/v1alpha1/register.go
tekton-listener/pkg/reconciler/eventbinding/reconciler.go
tekton-listener/pkg/reconciler/tektonlistener/reconciler.go

- Many fixes to the EventBinding and TektonListener resources. 
- Adds support for github push events for easy demoing
- Last milestone before the `Getting Started Guide` can be finished 👏 
review them:

So many eventbinding fixes

---

webhooks-extension/README.md
webhooks-extension/test/setup_webhook_simple_test.sh

This PR is to be merged alongside https://github.com/tektoncd/dashboard/pull/155 to ensure compatibility with the adjustments to the API to use plural nouns in routes.
Update CURLs to use new plural endpoints
review them:

Update CURLs to use new plural endpoints

---

tekton-listener/README.md
tekton-listener/docs/getting-started.md

The Readme for tekton-listener has old examples which are misleading - this updates those examples.
review them:

Update readme examples for TektonListener and EventBinding

---

tekton-listener/DEVELOPMENT.md
tekton-listener/README.md

And move some of the instructions to DEVELOPMENT.md
review them:

Link to getting started in tekton listener README

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss

Due to a code refactor, the create button was becoming float: left
aligned.  This change makes it float: right and corrects the common
scss naming.
review them:
- [ N/A ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

SCSS fix for create button alignment.

---

webhooks-extension/package-lock.json
webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

Fix for https://github.com/tektoncd/experimental/issues/72, use correct method name.
```
Test Suites: 9 passed, 9 total
Tests:       41 passed, 41 total
Snapshots:   0 total
Time:        19.272s
Ran all test suites.
```
All 41 tests now pass. I'm going to make a new issue for adding `npm run test` automatically next.
review them:

Refer to correct setShowNotificationOnTable function in tests

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/package-lock.json
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss

Change appearance and location of the add webhook button on the webhook display table.
Moved button and search in line with title and made add button kind=ghost with text colored green and aligned with plus icon
review them:
- [ - ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Change appearance and location of the add webhook button

---

OWNERS

/cc @bobcatfish 
review them:
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Add @mnuttall as root OWNER on experimental

---

test/publish-images.sh

:man_facepalming: 
/cc @mnuttall 
review them:
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

publish-images.sh: use the correct path to call sub scripts 🤕

---

test/publish-images.sh

I am really hoping this is the last one ! at least the scripts are executed now :angel: 
/cc @mnuttall 
review them:

publish-images.sh: use pushd/popd and a loop to get in the right folder

---

tekton-listener/test/publish-images.sh
webhooks-extension/test/publish-images.sh

publish-images.sh: don't fail on mkdir if the folder already exists

---

webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteDefaults.test.js

This is for https://github.com/tektoncd/experimental/issues/87
Resets the checkbox state for deleting PipelineRuns when we delete webhooks using the modal. Also added a test.
review them:

Reset delete runs checkbox to be unchecked on dialog show, add test

---

.gitignore
webhooks-extension/package-lock.json
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
webhooks-extension/test-it.sh
webhooks-extension/test/presubmit-tests.sh

Enable npm tests in prow on webhooks extension
review them:
- [ N/A ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Enable npm tests in prow on webhooks extension

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js

Remove dead/duplicate code
review them:

Remove dead code (deleteWebhook being registered twice)

---

webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml

Update the extension and sink services and deployment to use the tekton-pipelines namespace and tekton-dashboard service account
review them:

Install the extension release yaml in the tekton-pipelines namespace

---

webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
webhooks-extension/test/presubmit-tests.sh

Add a test that runs the npm build and then validates this as the value stored in the yaml file.
review them:
- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Add bundle hash code test to ensure yaml matches npm build output

---

webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/test/presubmit-tests.sh

For https://github.com/tektoncd/experimental/issues/95. 
Patch around https://github.com/tektoncd/plumbing/issues/44. 
Re-enable commented out webhook_tests, rewriting two of them.
review them:

Re-enable disabled webhook_tests

---

tekton-listener/test/publish-images.sh

So removing this part from the publish image script.
I promise, this is the last change @mnuttall :angel: :bowing_man: 
review them:

tekton-listener does not need `npm` 👼

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss

For https://github.com/tektoncd/experimental/issues/124 
Fix padding on webhooks modal button
review them:

Fix padding on webhooks modal button

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js

This change adds validation to the delete webhook button to ensure
that a webhook was selected in the table.
review them:
- [ n/a ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Show notification if no webhook selected for deletion.

---

webhooks-extension/cmd/extension/README.md
webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/package-lock.json
webhooks-extension/pkg/endpoints/credentials.go
webhooks-extension/pkg/endpoints/credentials_test.go
webhooks-extension/src/api/index.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js

For https://github.com/tektoncd/experimental/issues/69.
review them:

Use namespace in request body for creating secrets

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss

Style the password invisible toggle on Webhooks secret create panel
Stop the input box selection overlapping the eye icon, stop the text from overlapping also.
review them:

Style the password invisible toggle on Webhooks secret create panel

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/src/api/index.js
webhooks-extension/test_config/setupTests.js

https://github.com/tektoncd/dashboard/issues/290
- Update `getNamespace` and `getServiceAccounts` to use kube API via proxy
- Update `getPipelines` to use tekton API via proxy
Extension APIs remain as they are.
This will allow us to remove unused legacy dashboard APIs in https://github.com/tektoncd/dashboard/pull/313
Also updated some deps to reduce noise in the unit tests.
review them:

Update kube and tekton APIs to use proxy

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/package-lock.json
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js

Add lowContrast to InlineNotifications thus altering their colour scheme back to green and red backgrounds (the same as the main dashboard)
review them:

Adjust notifications to be consistent with main dashboard

---

webhooks-extension/DEVELOPMENT.md

This is for https://github.com/tektoncd/experimental/issues/131
Modify our docs - no longer need to reinstall the dash
review them:

Update dev docs, no longer need to reinstall dash for extension pickup

---

webhooks-extension/package-lock.json

npm was showing 16284 vulnerabilities resulting from https://www.npmjs.com/advisories/1013.  npm audit fix has been run and the resultant package-lock.json file uploaded.
review them:

Fix for vulnerability: https://www.npmjs.com/advisories/1013

---

webhooks-extension/OWNERS

Add dibbles as an approver
review them:

Increase privileges of dibbles to approver

---

webhooks-extension/pkg/endpoints/credentials.go
webhooks-extension/pkg/endpoints/credentials_test.go

Starred out the secret token for display in the webhook extension logs.
review them:

Secret token starred out in logs

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/package-lock.json
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss

Added a height limit for buttons on the table and made the toolbar invisible when not in use.
review them:

Webhooks table batch action bar visible in safari (issue #128)

---

webhooks-extension/OWNERS

Like with https://github.com/tektoncd/dashboard/pull/381, we should add @Megan-Wright as a reviewer here for the experimental webhooks-extension folder. Megan is replacing @jessm12 (unfortunately leaving us soon as a full time IBMer, but we hope will continue to contribute!) and plans to continue to contribute to this project (and to provide some reviews now 😸).
review them:

Add Megan Wright as reviewer for webhooks extension

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss

Implement consistency in UI components such as buttons, as well as text formatting
review them:

Implement consistency across UI components for webhooks extension

---

webhooks-extension/README.md

Additions made to the readme to detail some of the resources created by the sink triggered by the webhook.  This is to aid others currently looking at playing with the extension who may be trying to have the webhook trigger their own pipeline.
review them:

Update readme with details on sink

---

webhooks-extension/README.md

I have a working set up, didn't need to use .nip.io, documented everything i've done here
review them:
@mnuttall please take a look, here's my first draft (may need to fix the formatting for the route...see if it's off for you) 😄

Add OpenShift installation instructions including scc, route, cm settings

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.test.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js

issue: #179 
Previously I had it check if the last one was being deleted, now I changed the if statement to check if all the selected webhooks are all the webhooks in the table, then show the notification.

fix bug when deleting all webhooks in table

---

webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/sink-kservice.yaml

serviceAccountName must be specified in the config/*.yaml for developing against an RBAC-enforcing kube. 
review them:
- [n/a ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Fix dev yaml serviceAccountName

---

webhooks-extension/DEVELOPMENT.md
webhooks-extension/Gopkg.lock
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/sink-kservice.yaml
webhooks-extension/config/task-monitor-result.yaml
webhooks-extension/pkg/endpoints/sink.go
webhooks-extension/pkg/endpoints/types.go
webhooks-extension/pkg/endpoints/webhook_test.go

This is the refresh PR of #154 and #183
When the webhook triggers due to a pull request on the git repo, a pipelinerun is created along with a task to monitor its status. This task updates the pull request with the pipeline run result.
The default task used to update the pull request is monitor-result-task and the comment added to the pull request is either "OK" or "ERROR" along with a message based on the result of the pipelinerun.
The monitoring task can be overridden, on creation of the webhook (using the REST endpoint only) by setting the pulltask property in the POST body. The associated comments that get added to the pull request based on success or failure of the pipelinerun can be set using the onsuccesscomment (for success) and onfailurecoment (for failure) properties on the REST …

Update pull requests based on the result of the pipelinerun

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

When a notification first appears on the page auto scroll to the top of the page to view this notification. Don't auto scroll on subsequent page changes. 
review them:

Auto scroll to notification only once

---

webhooks-extension/README.md

Reference the release yaml assets for the webhooks extension.
For https://github.com/tektoncd/dashboard/issues/363 (our first release 🎈)!
review them:

Include release information docs for webhooks extension

---

webhooks-extension/README.md
webhooks-extension/tekton/README.md
webhooks-extension/tekton/build.yml

This is the process I followed for publishing a webhooks extension release and is largely based on instructions from https://github.com/tektoncd/dashboard/blob/master/tekton/README.md
review them:

Document publish process, bump release version in main readme to install

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteBasics.test.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteDefaults.test.js

refactor delete webhooks modal

---

webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/sink-kservice.yaml
webhooks-extension/config/task-monitor-result.yaml

For https://github.com/tektoncd/experimental/issues/202: include the `namespace` field. With @dibbles readme change we're recommending swapping out `tekton-pipelines` mentions with a target namespace of choice
I've also included :latest on the end of our image coordinates for the Python client. We have a task in our release pipeline that will (eventually for OpenShift too) look in the yaml files and replace it with a sha256sum so it's pinned at the time of release.
review them:

Include namespace in all yaml files for resources

---

webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/task-monitor-result.yaml

This PR is the fix for https://github.com/tektoncd/experimental/issues/229
The way update the PR has been changed.  The monitor task creates the files for the comment update and the status update instead of updating "pr.json" file.
review them:

monitor task update for pipeline 0.6.0

---

webhooks-extension/docs/Limitations.md

Documented bug with deletion of webhook.
review them:

Document bug with deletion of webhook

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

Correct the ordering of the help text on the create webhook panel and slightly modified the help text.  Issue 251.
review them:

Issue251: Correct the hover help on the create webhook panel

---

webhooks-extension/package-lock.json

Increased version of handlebars to 4.3.1 in package-lock.json
review them:

Up the version of handlebars to address https://npmjs.com/advisories/1164

---

webhooks-extension/docs/InstallReleaseBuild.md

Fixes the URL for the Kubernetes environments specific namespace instructions.
review them:
- [?] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Update URL for Kubernetes environments specific namespace

---

webhooks-extension/config/task-monitor-result.yaml
webhooks-extension/test/config.sh
webhooks-extension/test/setup_webhook_simple_test.sh
webhooks-extension/test/util.sh

Fixes: https://github.com/tektoncd/experimental/issues/265
https://github.com/pipeline-hotel/example-pipelines/pull/9 should be merged prior to this
Update Task Monitor to use new `$()` syntax since the old `${}` syntax is deprecated
Bump versioning within installation scripts
review them:

Update Task Monitor syntax and update prereq scripts

---

webhooks-extension/docs/InstallReleaseBuild.md

Now it's published, let people know they can use it
review them:

Reference 0.2.0 release in docs to use

---

webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/triggers_prototype/README.md
webhooks-extension/config/triggers_prototype/ingress.yaml
webhooks-extension/config/triggers_prototype/scripts/generate-certificate.sh
webhooks-extension/config/triggers_prototype/test/ingress-run.yaml

Alternative approach for https://github.com/tektoncd/experimental/issues/242 (make your own cert upfront, we'll use it)
review them:

Add Tekton Task and TaskRun to create and delete Ingress

---

webhooks-extension/pkg/endpoints/sink.go

Committed an error with PR https://github.com/tektoncd/experimental/pull/264 where we read the whole body & then try to read in again resulting in an EOF error. Now we copy the request before reading it completely. 
review them:

Duplicate Request Body before Reading it

---

webhooks-extension/docs/InstallPrereqs.md

Clearly calls out we're only known to be good and tested with this version, https://tektoncd.slack.com/archives/CHTHGRQBC/p1570705515006700?thread_ts=1570695293.003700&cid=CHTHGRQBC for some context

Mandate knative v0.6.0 as that's all we've tested

---

webhooks-extension/config/triggers_prototype/task-monitor-result.yaml
webhooks-extension/config/triggers_prototype/trigger-monitor-result.yaml

This is the initial code drop for the monitor task, triggerbindings and triggertemplate.  This is for the issue https://github.com/tektoncd/experimental/issues/244.
review them:

monitor task, bindings, template

---

webhooks-extension/docs/GettingStarted.md

Fixes #294
Add documentation about the 404 and 503 error.
/cc @a-roberts 
review them:

Add troubleshooting section to getting started doc

---

webhooks-extension/README.md
webhooks-extension/docs/GettingStarted.md
webhooks-extension/docs/InstallOnOpenshift.md
webhooks-extension/docs/example-openshift-configuration/maistra.yaml
webhooks-extension/docs/example-openshift-configuration/member-roll.yaml
webhooks-extension/docs/example-openshift-configuration/serving.yaml

For https://github.com/tektoncd/dashboard/issues/648

Add verified OpenShift 4.2 install and usage instructions

---

webhooks-extension/tekton/README.md
webhooks-extension/tekton/publish.yaml

Add test release instructions and cope with case when release bucket is empty in publish.yaml
review them:

Document test releases, and a small release code fix

---

webhooks-extension/Gopkg.lock
webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/test/presubmit-tests.sh

For https://github.com/tektoncd/experimental/issues/319

Check OpenShift yaml under openshift folder too

---

webhooks-extension/README.md
webhooks-extension/cmd/interceptor/interceptor.go
webhooks-extension/cmd/interceptor/interceptor_test.go
webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/docs/GettingStarted.md
webhooks-extension/docs/Labels.md
webhooks-extension/docs/Parameters.md
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
webhooks-extension/src/components/WebhookBranches/WebhookBranches.scss
webhooks-extension/src/components/WebhookBranches/tests/WebhookBranches.test.js

Modify the interceptor such that it makes a new parameter available in the event payload ()
Add docs for labeling of pipelineruns such that they display in the branches view of the webhook and for parameters made available to the triggertemplate.
review them:

Make branch name available fo use in labels, also supply docs

---

webhooks-extension/README.md
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/test/install_dashboard_and_extension.sh
webhooks-extension/test/util.sh

issue: #219 
Asks user which version he would like installed and from there do the necessary installation process.
review them:

Additional install script option to install nightly/release builds

---

webhooks-extension/cmd/interceptor/interceptor.go
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

This PR is for https://github.com/tektoncd/experimental/issues/250
The pull request is processed only when the action is one of opened, reopened or synchronize.
The event listener sends the actions to be processed in the header to the interceptor.  The interceptor checks if the action in the event matches one of the actions sent by the event listener if the actions are not empty.
review them:

check actions to process in the interceptor

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/monitor.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/src/components/WebhookBranches/WebhookBranches.js

Originally to address issue #358 might also address #360 but needs further testing.
- Update the href for the help URL on the branch listing modal.
- Add serviceaccount to the taskrun for the monitor triggertemplate in monitor.yaml
- Updates for npm reported high vulnerabilities
review them:

Update href on help link and add serviceaccount to monitor

---

webhooks-extension/Gopkg.lock
webhooks-extension/package-lock.json
webhooks-extension/package.json

Noticed and ran `npm audit fix`, here we go

Audit fix - React and Handlebars

---

vendor/github.com/tektoncd/plumbing/scripts/library.sh
vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
webhooks-extension/cmd/interceptor/interceptor.go

As the title suggest :angel: 
review them:

Bump tektoncd/plumbing dependency ⛽️

---

catalogs/OWNERS
catalogs/cmd/catalogs/main.go
catalogs/go.mod
catalogs/go.sum
catalogs/test/presubmit-tests.sh
test/presubmit-tests.sh

Based on the [Tekton catalog integration proposal](https://docs.google.com/document/d/1O8VHZ-7tNuuRjPNjPfdo8bD--WDrkcz-lbtJ3P8Wugs/edit#heading=h.iyqzt1brkg3o), 
This folder/repository would host [Catalog resource](https://docs.google.com/document/d/1O8VHZ-7tNuuRjPNjPfdo8bD--WDrkcz-lbtJ3P8Wugs/edit#heading=h.2g5p8k503yjk) part of the proposal.
/cc @sthaha 
Closes tektoncd/community#53
This adds a new CRD, name Catalog, which allow the user to refer which catalog to register on the cluster. This would also bring a `tkn-catalog` binary (that could be taken into account by `tkn`) to interact with those CR.
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Catalog
metadata:
name: upstream
spec:
url: https://github.com/tektoncd/catalog
revision: v0.7 # optional, default would be master or the …
```

Initialize the catalogs project.

---

octant-plugin/OWNERS
octant-plugin/go.mod
octant-plugin/go.sum
octant-plugin/test/presubmit-tests.sh
test/presubmit-tests.sh

- Remove `octant-plugin` binary the repository :stuck_out_tongue_closed_eyes: 
- Enable *tests* on `octant-plugin`
/cc @ImJasonH 
review them:

octant-plugin cleanups

---

webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/monitor.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml

For: https://github.com/tektoncd/experimental/issues/384
Fixes bug in 'Success' message on a pull request to redirect to the correct URL.
Also fixes the 'Fail' message to direct to the same URL.
review them:

Fixed bad URL for webhooks 'Success' message

---

octant-plugin/README.md

This pull request adds more details about using the Tekton plugin for Octant. It details how to add the plugin binary to the Octant plugins folder, touches up the development/testing section, and also shows to uninstall the plugin.
review them:

Update Octant Plugin Documentation

---

webhooks-extension/tekton/publish.yaml

Modified `image: gcr.io/tekton-releases/ko-ci` to `image: gcr.io/tekton-nightly/ko-ci` in tekton/publish.yaml
review them:
- [n/a ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Modify ko-ci image referenced in release process yaml

---

webhooks-extension/tekton/publish.yaml

Release process needs an update to use kustomize. For https://github.com/tektoncd/experimental/issues/406. No README changes required. 
review them:

Use kustomize in release process

---

test/presubmit-tests.sh

Should help inital commit for projects, #413 
/cc @ImJasonH 
review them:

Skip instead of failing if a project doesn't provide a presubmit-tests

---

webhooks-extension/README.md
webhooks-extension/docs/InstallNightlyBuild.md
webhooks-extension/docs/InstallPrereqs.md
webhooks-extension/docs/InstallReleaseBuild.md

This PR is for https://github.com/tektoncd/experimental/issues/401
Minor changes for v0.3.0 in
README.md
docs/InstallNightlyBuild.md
docs/InstallReleaseBuild.md
docs/InstallPrereqs.md
review them:

Update webhooks doc for 0.3.0 release

---

webhooks-extension/docs/GettingStarted.md
webhooks-extension/docs/InstallNightlyBuild.md
webhooks-extension/docs/InstallReleaseBuild.md

This PR for issue https://github.com/tektoncd/experimental/issues/343
Add additional information to setup webhook extension in Amazon EKS environment.
Changed file:
GettingStarted.md
InstallNightlyBuild.md
InstallReleaseBuild.md
review them:

Update with EKS environment information

---

webhooks-extension/overlays/openshift-all/deployment-patch.yaml
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

make https for default protocol for webhook in OpenShift

---

webhooks-extension/docs/NotesOnOpenShiftInstallations.md

This PR is for https://github.com/tektoncd/experimental/issues/416
Add OpenShift internal docker registry URL for OpenShift 3.11 in NotesOnOpenShiftInstallations.md.
review them:

Add OpenShift registry URL for 3.11

---

webhooks-extension/base/400-monitor-task.yaml

For https://github.com/tektoncd/experimental/issues/442

Don't pass the PullRequest if no PipelineRuns ever found for it

---

webhooks-extension/DEVELOPMENT.md
webhooks-extension/build-it.sh
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/test/presubmit-tests.sh

It's irritating to constantly change the hash after changing web code, so under this PR make it no longer required = though you do need yq

Automatically use the generated hash for your service yaml

---

webhooks-extension/build-it.sh

Update build-it.sh to look for directories instead of files - looking for files was causing the script to fail.
review them:

Change build script to look for directories instead of files

---

webhooks-extension/cmd/interceptor/gitlab.go

Changes the URL check to ensure the target of the merge request is the project on which the webhook is configured (rather than the source repo URL matching)
review them:

Fix gitlab interceptor URL check

---

oci/pkg/action/pull.go
oci/pkg/oci/bundle.go
oci/pkg/oci/image.go

- No functional change; only a minor cleanup
review them:
- [🙅] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

OCI: minor code cleanup

---

webhooks-extension/tekton/build.yml

For https://github.com/tektoncd/experimental/issues/457

Install yq in build pipeline

---

webhooks-extension/src/components/WebhookBranches/WebhookBranches.js

Fixes https://github.com/tektoncd/experimental/issues/478, probably need a new hash
review them:

Use correct URL for getting help

---

webhooks-extension/DEVELOPMENT.md
webhooks-extension/Gopkg.lock
webhooks-extension/Gopkg.toml
webhooks-extension/base/200-clusterrole-eventListener.yaml
webhooks-extension/base/200-clusterrole.yaml
webhooks-extension/base/200-role.yaml
webhooks-extension/base/300-extension-service.yaml
webhooks-extension/base/400-monitor-task.yaml
webhooks-extension/base/400-monitor-triggerbinding.yaml
webhooks-extension/base/400-monitor-triggertemplate.yaml
webhooks-extension/docs/InstallPrereqs.md
webhooks-extension/docs/Limitations.md
webhooks-extension/docs/Parameters.md
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/src/api/index.js
webhooks-extension/test/config.sh

Also makes the webhook name necessary to be unique.
For https://github.com/tektoncd/experimental/issues/493
review them:

Tekton Triggers 0.4 support for webhooks extension

---

helm/pipeline/Chart.yaml
helm/pipeline/README.md
helm/pipeline/values.yaml

This PR updates pipelines helm chart to the new v0.11.1 version.

Upgrade helm pipelines images to v0.11.1

---

helm/dashboard/Chart.yaml
helm/pipeline/Chart.yaml
helm/triggers/Chart.yaml

This PR adds icons in helm charts descriptions.

Add icons in charts description

---

helm/.hack/check-helm-docs.sh
helm/.hack/check-version.sh

This PR adds a script to check chart version is incremented when a chart is modified.
Related issue: https://github.com/tektoncd/plumbing/issues/337

Add script to check chart version is incremented when a chart is modified

---

helm/.hack/check-version.sh

Helm chart changes are not detected due to missing git commands.

Fix helm chart changes not detected

---

oci/README.md
vendor/github.com/tektoncd/plumbing/scripts/library.sh
vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
webhooks-extension/test/presubmit-tests.sh

This adds a README and also helps me test tektoncd/plumbing `test-runner` changes :sweat_smile: 
review them:

oci: add a README.md

---

helm/dashboard/README.md
helm/dashboard/templates/clusterrole.yaml
helm/dashboard/templates/extension.yaml
helm/dashboard/values.yaml

This PR adds support for dashboard extensions in the dashboard helm chart.
review them:

[helm/dashboard] add extensions support

---

webhooks-extension/base/200-clusterrole-eventListener.yaml
webhooks-extension/base/200-clusterrole.yaml
webhooks-extension/base/200-role.yaml
webhooks-extension/base/200-serviceaccount-eventListener.yaml
webhooks-extension/base/200-serviceaccount.yaml
webhooks-extension/base/201-clusterrolebinding-eventListener.yaml
webhooks-extension/base/201-clusterrolebinding.yaml
webhooks-extension/base/201-rolebinding.yaml
webhooks-extension/base/300-extension-deployment.yaml
webhooks-extension/base/300-extension-service.yaml
webhooks-extension/base/300-interceptor-deployment.yaml
webhooks-extension/base/300-interceptor-service.yaml
webhooks-extension/base/400-monitor-task.yaml
webhooks-extension/base/400-monitor-triggerbinding.yaml
webhooks-extension/base/400-monitor-triggertemplate.yaml
webhooks-extension/overlays/openshift-all/deployment-patch.yaml
webhooks-extension/overlays/plainkube-all/deployment-patch.yaml
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/test/dashboard-service.yaml

This PR adds recommended k8s labels on resources.
This is the implementation for proposal https://github.com/tektoncd/pipeline/issues/2497
- Added labels on all k8s resources.
- Changed go code for looking up dashboard resources

[webhooks-extension] add recommended k8s labels

---

webhooks-extension/base/300-extension-service.yaml
webhooks-extension/src/api/comms.js
webhooks-extension/src/api/index.js
webhooks-extension/src/api/tests/comms.test.js
webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
webhooks-extension/src/test/utils/test.js

https://github.com/tektoncd/experimental/issues/540
Add support for the CSRF token required by Dashboard (tested against Dashboard master) on any mutating request (POST, PUT, DELETE, etc.)
review them:

webhooks-extension: Add support for CSRF token

---

webhooks-extension/docs/InstallPrereqs.md
webhooks-extension/test/util.sh

Current link's a 404 so use this, tested on Docker Desktop
review them:

Document + use in test new nginx install method

---

helm/dashboard/Chart.yaml
helm/dashboard/README.md
helm/dashboard/templates/clusterrole.yaml

This PR fixes an issue with incorrect triggers api group in RBAC.
Closes #535 
/cc @vdemeester 
review them:

[helm/dashboard] Fix triggers api group in RBAC

---

webhooks-extension/overlays/openshift-all/kustomization.yaml

Closes #522
One liner that saves me replacing tekton-pipelines everywhere on OpenShift
review them:

Install webhooks extension on openshift to openshift-pipelines, matching Dashboard

---

webhooks-extension/docs/InstallReleaseBuild.md

Changes the install yaml to be the correct one for other kubernetes environments 
review them:

update other kubernetes enviroments install yaml name

---

webhooks-extension/OWNERS

Removes Jess, Vincent and Aki from the list of reviewers - the first two no longer being part of the team and Aki having other priorities.
/cc @a-roberts 
review them:

Remove inactive users from reviewers list

---

commit-status-tracker/go.sum
commit-status-tracker/pkg/controller/pipelinerun/client_test.go
commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller.go
commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller_test.go
commit-status-tracker/pkg/controller/pipelinerun/resource.go
commit-status-tracker/pkg/controller/pipelinerun/resource_test.go

This PR will provide support for the operator to send the commit status to a GitLab repository. This involves detecting the repository type and using its client.
review them:

Allow status tracker to send commit status to a GitLab repository

---

hub/api/.ko.yaml
hub/docs/development.md

Fixes api service that requires a base-image which has `git` 
review them:
- [🙅  ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Hub: fix api deployment

---

webhooks-extension/Gopkg.lock
webhooks-extension/Gopkg.toml
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

Changes to make webhooks work with master of triggers which should be triggers 0.6.0 release 
Thanks to @ncskier and @Megan-Wright for helping 😸 
review them:

Make webhooks work with triggers master

---

results/OWNERS

Adds OWNERS file for results directory.
review them:

Add results/OWNERS

---

hub/docs/prod-deployment.md

This adds a doc for Hub to deploy to production:
- Deploying a New Instance &
- Upgrading to a New Release
review them:

Hub: Adds doc stating steps to deploy to production

---

hub/README.md

Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>
review them:

Modifies README.md and adds deployed application link

---

hub/docs/prod-deployment.md

Changes: 
- Add the step to populate data from catalog in db
- sync the db for any catalog changes after a release
review them:

Hub: Fix prod-doc for sync db step

---

hub/ui/src/components/footer/Footer.tsx

Replace Red Hat copyright with tekton.dev copyright in Hub footer.
review them:

Hub:Replace Red Hat copyright with tekton.dev copyright

---

hub/ui/src/components/footer/Footer.tsx

Changes CD foundation logo size in footer.
review them:

Hub:Resizes CD foundation logo in footer

---

hub/api/config/21-api-deployment.yaml
hub/api/config/db-migration/14-db-migration.yaml

This updates the ko import path in deployment and DB-migration.
review them:

Hub: Google/ko 5.0+ requires images to be prefixed by ko://

---

hub/api/pkg/git/repo.go

Use tekton specific annotations instead of generic ones
See: https://github.com/tektoncd/community/pull/123#discussion_r452469685
review them:
- [🙅 ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Hub: use tekton specific annotations for tags and displayName

---

hub/api/pkg/db/model/migration.go

Now that the catalog follows the Catalog re-org TEP, lets use that
as the default community catalog.
review them:
- [🙅 ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Hub: switch to upstream catalog

---

results/README.md
results/cmd/api/main_test.go
results/cmd/api/results.sql
results/go.sum

This ensures that the same schema is used for real and test servers.
Also includes a few minor cleanups in setupTestDB:
- Split `t.Cleanup` into 2 Cleanups in order to ensure that Cleanups occur
even if there is a partial failure.
- Use `t.Helper` in setupTestDB helper func.
- Remove usused variable from setupTestDB.
review them:
/assign @yuege01

Results: Read test DB schema from file.

---

hub/api/config/00-namespace.yaml
hub/api/config/10-db-secret.yaml
hub/api/config/11-db-pvc.yaml
hub/api/config/12-db-deployment.yaml
hub/api/config/13-db-service.yaml
hub/api/config/20-api-secret.yaml
hub/api/config/21-api-deployment.yaml
hub/api/config/22-api-service.yaml
hub/api/config/23-api-ingress.yaml
hub/api/config/db-migration/14-db-migration.yaml
hub/api/config/openshift/22-api-route.yaml
hub/api/pkg/api/handlers.go
hub/api/pkg/routes/routes.go
hub/ui/config/00-namespace.yaml
hub/ui/config/10-config.yaml
hub/ui/config/11-deployment.yaml
hub/ui/config/12-service.yaml
hub/ui/config/13-ingress.yaml
hub/ui/config/openshift/13-route.yaml

Deploys Hub to GKE 
review them:

Hub: deploy on gke

---

hub/api/config/db-migration/15-db-cronjob.yaml

This will run a cron job every 10 minutes which will sync catalog
changes to db.
review them:

Hub: Add cronjob to sync catalog changes to db at regular interval

---

hub/ui/src/components/task/Task.tsx
hub/ui/src/components/task/index.css

- Previously,summary was missing for few resources on resource card.
- This patch adds missing summary for resources.
review them:

Hub: Fixes summary of a resource on the resource card

---

hub/ui-new/src/components/description/CodeBlockReadme.tsx
hub/ui-new/src/components/description/Description.tsx
hub/ui-new/src/components/description/index.css
hub/ui-new/src/components/rating/index.css
hub/ui/src/components/description/CodeBlockReadme.tsx
hub/ui/src/components/description/Description.tsx
hub/ui/src/components/description/index.css
hub/ui/src/components/rating/index.css

Modifies Markdown rendering on detail page

---

hub/ui-new/src/components/description/Description.tsx
hub/ui-new/src/components/detail/Detail.tsx
hub/ui/src/components/description/Description.tsx
hub/ui/src/components/detail/Detail.tsx

Previously the description detail background was not centered 
For e.g:
Changes made to make detail background to be aligned at center
review them:

Aligns Task detail background to center

---

hub/ui-new/src/components/rating/Rating.tsx
hub/ui-new/src/components/rating/index.css
hub/ui/src/components/rating/Rating.tsx
hub/ui/src/components/rating/index.css

Initial rating icons:
Modified rating icons :
review them:

Hub: Modifies the rating icons on detail page

---

hub/ui-new/package-lock.json
hub/ui-new/src/components/task/Task.tsx
hub/ui/package-lock.json
hub/ui/public/config.js
hub/ui/src/components/task/Task.tsx

Hub: Fix minor UI changes

---

generators/pkg/generator/generate.go
generators/pkg/generator/generate_test.go
generators/pkg/generator/testdata/pipeline1.yaml
generators/pkg/generator/testdata/run.yaml
generators/pkg/generator/testdata/run1.yaml
generators/pkg/generator/testdata/run2.yaml
generators/pkg/generator/testdata/taskrun.yaml
generators/pkg/writer/testdata/config.yaml
generators/pkg/writer/write.go

This PR aims to add the alternative configs (pipelinerun) for users to run the pipeline for [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590).
The changes include:
1. Add support to generate pipelinerun for users to run. Because we want to provide more ways for users to run, not only the triggers.
2. Change the StringVal `$(params.gitrevision)` to `github.Spec.Revision` in the params of pipeline, because param substitution wasn't working properly with finally for the time being. This change can be removed when this param substitution bug is fixed in the future.
review them:

Add support for PipelineRun in pkg

---

generators/README.md

This PR aims to refine the README for [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590).
The main change is to use the content of Tekton generators design doc to merge into the
README. The refined README is more like a 'user manual'.
review them:

Merge the content of design doc to the README for Tekton Generators

---

generators/cmd/cli/cmd/pipelinerun/apply.go
generators/cmd/cli/cmd/pipelinerun/delete.go
generators/cmd/cli/cmd/pipelinerun/pipelinerun.go
generators/cmd/cli/cmd/pipelinerun/show.go
generators/cmd/cli/cmd/pipelinerun/write.go
generators/cmd/cli/cmd/root.go
generators/cmd/cli/cmd/trigger/show.go
generators/cmd/cli/cmd/trigger/write.go
generators/pkg/writer/testdata/run.yaml
generators/pkg/writer/write.go
generators/pkg/writer/write_test.go

This PR aims to add the new PipelineRun subcommand for users to run the pipeline for [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590).
The changes include:
1. Add support to write pipelinerun for users to run. Extract the similar codes to
functions like `parseFile()`, `getResource()`
2. Add new PipelineRun subcommand to the CLI. Same as `trigger`, it contains four subcommands as well.
review them:

Add new PipelineRun subcommand

---

hub/ui-new/src/components/basic-detail/BasicDetail.tsx
hub/ui-new/src/components/main/App.tsx
hub/ui-new/src/components/rating/Rating.tsx
hub/ui/src/components/basic-detail/BasicDetail.tsx
hub/ui/src/components/main/App.tsx
hub/ui/src/components/rating/Rating.tsx

this patch includes
- fixes space among resource cards on homepage.
- removes resource name on detail page and add it to resource github link.
review them:

Hub: modifies homepage UI and resource detail page

---

hub/api/config/db-migration/15-db-cronjob.yaml

Updates cronjob scheduled to run every 30 min. 
review them:

Hub: Updates cronjob to run sync every 30 min

---

hub/api/pkg/service/category.go
hub/api/pkg/service/resource.go

Hub: Fixes trailing spaces in api response

---

hub/api/pkg/git/repo.go
hub/api/pkg/service/category.go
hub/api/pkg/service/resource.go

Hub: Fixes trailing spaces in api

---

webhooks-extension/docs/InstallReleaseBuild.md

Update the webhooks-extension install docs to add a deprecation notice
and update the install commands to reference the last available release
(v0.7.0).
review them:

Update webhooks-extension docs to reference last release - v0.7.0

---

results/.gitattributes

@dibyom 
Adds .gitattributes file (https://git-scm.com/docs/gitattributes) for
annotaing generated code for GitHub Linguist
(https://github.com/github/linguist).
review them:

Results: Add .gitattributes file.

---

hub/ui/src/components/background-image/image.css
hub/ui/src/components/rating/Rating.tsx

Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>
review them:

Hub: Modifies header height

---

results/README.md
results/cmd/watcher/main.go
results/config/api.yaml
results/config/watcher.yaml

- Adds placeholder for required environment vars.
- Fixes service DNS address.
- Changes service port to 50051 to make it easier to port forward for
local testing.
- Adds insecure auth mode for connecting to API servers without
credentials.
review them:

Results: Fix k8s service yaml for on-cluster support.

---

hub/ui/src/components/main/App.tsx
hub/ui/src/components/main/index.css

Add feature to copy hub token from the frontend and also modified UI in the toolbar.
review them:

Hub: Add hub token copy feature

---

hub/ui/src/components/filter/Filter.tsx
hub/ui/src/components/redux/Actions/ResourcesList.tsx
hub/ui/src/components/redux/Actions/TaskAction.tsx
hub/ui/src/components/redux/Actions/TaskDataListAction.tsx

This updates UI according to change in API response as now the it will
be returned inside an object with key as 'data'.
review them:

Hub: Updates UI according to changes in API response

---

hub/ui/src/components/basic-detail/BasicDetail.tsx
hub/ui/src/components/basic-detail/BasicDetailParent.tsx
hub/ui/src/components/redux/Actions/TaskActionName.tsx

This updates UI according to change in API response as now it will
be returned inside an object with key as 'data'.
review them:

Hub: Updates UI acc to changes in API response for list of versions

---

.github/pull_request_template.md

When browsing the git log, it may be challenging to identify commits
that belong to a specific project in experimental.
This proposes to "tag" commit message subjects with the name of
the project into square brakets.
review them:

[experimental] Add project tag for commit in the PR template

---

sdk/python/examples/taskrun.ipynb
sdk/python/setup.py
sdk/python/tekton/api/tekton_client.py
sdk/python/tekton/models/v1beta1_when_expression.py

The PR is going to:
1. fix SDK bug that `duplicate argument 'input' in function definition` in v1beta1_when_expression.py
2. Updated `delete` API due to k8s Python client changed.
3. Updated SDK examples.
review them:

Fix SDK bug and update SDK examples

---

results/pkg/api/server/server.go
results/pkg/api/server/server_test.go

Updates the env settings for CEL(declares one more variable called `pipelinerun`), 
and endows the List Results API in `server.go` the ability to filter the results fetched 
from the database by either `taskrun` or `pipelinerun` or both.
review them:

[results] Supports to Filter PipelineRun in List API

---

results/cmd/watcher/main.go
results/pkg/watcher/reconciler/annotation/annotation.go
results/pkg/watcher/reconciler/internal/test/clients.go
results/pkg/watcher/reconciler/internal/test/reconcile.go
results/pkg/watcher/reconciler/pipelinerun/pipelinerun.go
results/pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
results/pkg/watcher/reconciler/reconciler_test.go
results/pkg/watcher/reconciler/taskrun/taskrun.go
results/pkg/watcher/reconciler/taskrun/taskrun_test.go

The helper common packages were pulling in `knative.dev/pkg/test` which
had a flag conflict with `knative.dev/pkg/injection/sharedmain`. This
separates the packages to remove this dependency. There should be no
change in behavior here.
review them:

[results] Refactor helper packages to remove test deps.

---

commit-status-tracker/README.md

minor fixes to README.md:
* dep_tool not used
* operator_sdk vs. operator_install
review them:

[commit-status-tracker] Fix broken references in README.md

---

results/pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
results/pkg/watcher/reconciler/taskrun/taskrun_test.go

I don't fully understand why this was sometimes passing before, but
the likely guess is that the reconciler was updating the pointer
reference somewhere, or test ordering was interfering with results with
the same name.
This resolves the problem by doing 2 things:
1. Always use a fresh results server / reconciler for each test. This
helps prevent test crossover / ordering from affecting the output.
2. Do an initial reconcile instead of a Get to ensure that all the
necessary IDs are set.
Tested that `go test -count 50 ./pkg/watcher/reconciler/...` works,
which should give us decent confidence that this is fixed.
review them:
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#pr …

[results] Fix flaky reconciler tests.

---

results/pkg/api/server/v1alpha2/results.go
results/pkg/api/server/v1alpha2/results_test.go

Implements v1alpha2 Results.Delete.
This is largely carried over from the v1alpha1 implementation.
review them:

[results] Implement v1alpha2 Results.Delete.

---

results/LICENSE

Adds explicit LICENSE file.
This is in preparation for the cut-over to the new results repo.
review them:

[results] Add explicit LICENSE file.

---

cel/OWNERS

Kevin has done a lot of work in Triggers CEL interceptor and has reviewed the initial PR for the project, thank you @bigkevmcd 🙏🏾
review them:

[CEL] Add  Kevin McDermott to Owners

---

task-loops/OWNERS

Add Jason as owner of the task-loops project
review them:
/cc @bobcatfish @vdemeester

[task-loops] Add Jason as owner of the task-loops project

---

task-loops/tekton/README.md
task-loops/tekton/kustomization.yaml
task-loops/tekton/publish.yaml
task-loops/tekton/release-pipeline.yaml

Add the tasks and pipelines required for nightly builds of task
loops. These resources will be deployed and triggered through
the nightly builds infra defined in the plumbing repo.
review them:

[task-loops] Add tekton resources to build task-loops

---

task-loops/tekton/publish.yaml

[task-loops] Fix typo in auth script
review them:

[task-loops] Fix typo in auth script

---

cel/tekton/publish.yaml
cel/tekton/release-pipeline.yaml
pipelines-in-pipelines/tekton/publish.yaml
pipelines-in-pipelines/tekton/release-pipeline.yaml

The release pipelines for PIP and CEL were inspired by that of
task-loops. PIP and CEL do not have a vendor folder, they rely
on go modules, so a few tweaks are needed for build and unit tests
to run successfully.
review them:

[pip][cel] Fix build and unit tests for pip and cel

---

cel/tekton/release-pipeline.yaml
pipelines-in-pipelines/tekton/release-pipeline.yaml

In a previous PR, the build task in the release pipeline was
renamed, but I missed to update the dependency to that task,
so fixing that now.
review them:

[pip][cel] Fix the name of the build-tests task

---

wait-task/cmd/controller/main.go
wait-task/config/controller.yaml

Move the main module to cmd/controller so that it's aligned with
pipeline and other custom tasks and compatible with `koparse` that
we use for release purposes.
review them:

[wait-loop] Move main into cmd/controller

---

vendor/github.com/tektoncd/plumbing/scripts/README.md
vendor/github.com/tektoncd/plumbing/scripts/dummy.go
vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
vendor/github.com/tektoncd/plumbing/scripts/library.sh
vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh

Update the scripts vendored from plumbing to the latest version at
sha 4eafc733d5ddd8c4c46cc5519650d411f6a62c04.
This fixes the issue with basic authentication and k8s v1.19.
review them:
> Not project specific
/kind misc

Update the scripts vendored from plumbing

---

notifiers/github-app/OWNERS

[notifiers] GitHub: Add OWNERS file
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

[notifiers] GitHub: Add OWNERS file

---

vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
webhooks-extension/test/presubmit-tests.sh

Bump plumbing to https://github.com/tektoncd/plumbing/commit/b2459312cc6b5116a3fe728207b8f76234182260 to fix test script causing all tests to run.
Also disables go modules for webhooks-extension, since it is not
compatible and is failing tests.
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [-] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

Bump plumbing to b245931

---

notifiers/github-app/cmd/main.go
notifiers/github-app/pkg/controller/common_test.go
notifiers/github-app/pkg/controller/controller_test.go
notifiers/github-app/pkg/controller/github_test.go
notifiers/github-app/pkg/controller/template.md
notifiers/github-app/pkg/controller/template_test.go
notifiers/github-app/pkg/controller/testdata/taskrun-incomplete.md.golden
notifiers/github-app/pkg/controller/testdata/taskrun-incomplete.yaml

This changes fixes a few things that slipped by
https://github.com/tektoncd/experimental/pull/662 due to some bitrot.
- Updates Knative context code to disable leader election for the time
being.
- Updates templates to handle in-progress TaskRuns where fields may
be missing (e.g. CompletionTime, etc).
review them:

[notifiers] GitHub App: Fix broken knative context and template.

---

pipelines-in-pipelines/OWNERS

I'd like to help get pipelines in pipelines PRs
merged by lgtm'ing.

[pipelines-in-pipelines] Add sbwsg for lgtm

---

pipelines-in-pipelines/README.md

Users have been installing `ko` and using it to build and install the
controller on their clusters
We now have a Cron Job that builds a nightly release
https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly
This change adds documentation for installing from the nightly release
/kind documentation
review them:

[pipelines-in-pipelines] install from nightly release

---

cloudevents/pkg/reconciler/events/events.go
cloudevents/pkg/reconciler/pipelinerun/reconciler.go
cloudevents/pkg/reconciler/pipelinerun/reconciler_test.go

Add handling of the start event and some more unit test coverage
for the reconciler.
review them:

[cloudevents] Add handling of start event

---

cloudevents/go.sum
cloudevents/pkg/reconciler/events/cloudevent/artifacts.go
cloudevents/pkg/reconciler/events/cloudevent/artifacts_test.go
cloudevents/pkg/reconciler/events/cloudevent/cloudevent.go
cloudevents/pkg/reconciler/events/cloudevent/interface.go
cloudevents/pkg/reconciler/events/cloudevent/services.go
cloudevents/pkg/reconciler/events/cloudevent/services_test.go
cloudevents/pkg/reconciler/pipelinerun/reconciler_test.go

[cloudevents] Add events for services
Add for events for services:
- deployed
- rolledback
- upgraded
- removed
review them:

[cloudevents] Service events

---

cloudevents/pkg/reconciler/events/cloudevent/cloudevent.go

In case one of the event kinds cannot be sent, continue with the
next ones.
review them:

[cloudevents] Loop through all event kinds

---

cloudevents/config/config-defaults.yaml
cloudevents/go.mod
cloudevents/go.sum
cloudevents/pkg/reconciler/events/cache/cache.go
cloudevents/pkg/reconciler/events/cache/cache_test.go
cloudevents/pkg/reconciler/events/cache/cacheclient.go
cloudevents/pkg/reconciler/events/cloudevent/cloudevent.go
cloudevents/pkg/reconciler/pipelinerun/controller.go
cloudevents/pkg/reconciler/pipelinerun/reconciler.go
cloudevents/pkg/reconciler/pipelinerun/reconciler_test.go

- Inject LRU Cache to the context.Context
- Update cache if event is sent.
- Disallow sending duplicate events by checking the cache
review them:

[cloudevents] Add cache for tracking state of cloudevents

---

notifiers/github-app/config/deployment.yaml

Sets MIN_KUBERNETES_VERSION to be compatible with current dogfooding cluster version. This is required by Knative to start up properly.
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

[notifiers/GitHub] Sets MIN_KUBERNETES_VERSION

---

workflows/OWNERS
workflows/README.md

Add initial OWNERS file and Readme for workflows 
ref: tektoncd/community#464
review them:

[workflows] Add initial OWNERS and Readme

---

CONTRIBUTING.md
README.md
cel/README.md
generators/README.md
task-loops/README.md

This isn't an exhaustive list but wanted to at least get it started!
I completely missed the presubmit-tests.sh update and @jerop caught it
for me but wanted to document this for folks in the future.
To be thorough we should also add more about how to add all the files
you need for your project (e.g. even that presubmit script assumes
certain other scripts are in the project folder)
review them:
- [n/a] Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

Add instructions for new projects + fix links 📝

---

cel/OWNERS

@wlynch has reviewed https://github.com/tektoncd/experimental/pull/784 where we introduce cel custom tasks crd -- so adding him as an owner so he has approval permissions
review them:
_See [the contribution guide](https://github.com/tektoncd/experimental/blob/master/CONTRIBUTING.md) for more details._

[cel] add wlynch as an owner

---

workflows/OWNERS

@chmouel @khrm are interested in being maintainers for the project!
review them:

[Workflows] Add  @chmouel and @khrm as approvers

---

pipeline-to-taskrun/README.md

Now that we have a working nightly build of pipeline-to-taskrun
(thanks again @nikhil-thomas!) users don't have to install with
`ko` (unless they want to make changes)
cc @lbernick
review them:

[pipeline-to-taskrun] Add nightly install instructions 👀

---

workflows/OWNERS

Based on discussion in the Workflows/Pipelines as Code Working Group on March 1
review them:

[workflows] Add @savitaashture as an approver

---

pipeline/trusted-resources/OWNERS
test/presubmit-tests.sh

Initial directory creation with initial OWNERS file. Proposed and
approved in https://github.com/tektoncd/experimental/issues/834 by @bobcatfish @vdemeester 
Docs to come with implementation (see https://github.com/tektoncd/experimental/pull/833)
review them:

[pipeline/trusted-resources] Add OWNERS file.

---

cloudevents/tekton/release-pipeline.yaml

[cloudevents] Tweak nightly build resources 
review them:

[cloudevents] Tweak nightly build resources

---

cloudevents/tekton/publish.yaml

[cloudevents] Fix the publish task to make creds discoverable
review them:

[cloudevents] Fix the publish task to make creds discoverable

---

pipeline/trusted-resources/.gitignore
pipeline/trusted-resources/README.md
pipeline/trusted-resources/cmd/sign/main.go
pipeline/trusted-resources/cmd/sign/sign_test.go
pipeline/trusted-resources/examples/1-test-taskrun-signed.yaml
pipeline/trusted-resources/examples/2-test-taskrun-oci-bundle-signed.yaml
pipeline/trusted-resources/examples/3-test-taskrun-taskref-signed.yaml
pipeline/trusted-resources/examples/4-test-taskrun_fail_verification.yaml
pipeline/trusted-resources/go.mod
pipeline/trusted-resources/pkg/trustedtask/sign.go
pipeline/trusted-resources/pkg/trustedtask/sign_test.go
pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go

This commit adds some signing code and examples for users to generate
signed taskrun yaml files.
Prior to this commit, this part is missing and some code is not public.
review them:

[pipeline/trusted-resources]Add signing for yaml files

---

pipeline/trusted-resources/config/200-clusterrole.yaml
pipeline/trusted-resources/config/500-webhook-trusted-resources.yaml

This commit will remove not used mutating webhook config and add missing
config.
review them:

[pipeline/trusted-resources]Clean config files

---

pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go

This commit focus on verify the task which is applied in cluster and
referred in taskrun. In this commit we will exclude system populated
fields and keep fields from users. The reason we verify the task in
taskrun validation not the task's validation is that there is a stage
between task creation and taskrun creation, so we need to make sure the
task is not tampered.
Before this commit we can only verify task from oci bundle.
review them:

[pipeline/trusted-resources]Verify task from cluster at taskrun

---

pipeline-in-pod/LICENSE
pipeline-in-pod/OWNERS
pipeline-in-pod/README.md

This commit adds a license, readme, and owners for a new experimental project
for running a pipeline in a pod.
review them:

Add experimental directory for pipeline in a pod

---

pipeline/trusted-resources/OWNERS

Add @XinruZhang as an owner of this experimental project.
review them:

[pipeline/trusted-resources] Add An Owner

---

pipelines-in-pipelines/README.md

fixes https://github.com/tektoncd/experimental/issues/817
Replace authenticated nightly release url with the pulblic access url (as also in https://github.com/tektoncd/experimental/pull/816).
review them:

Fix install url in pipelines-in-pipelines README

---

pipeline-in-pod/README.md
pipeline-in-pod/examples/inline-pipeline-inline-tasks.yaml
pipeline-in-pod/examples/inline-pipeline-taskrefs.yaml
pipeline-in-pod/examples/pipelineref.yaml
pipeline-in-pod/go.sum
pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocatedpipelinerun_types.go
pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/zz_generated.deepcopy.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/apply.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/entrypoint.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/ordering.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelineinpod.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelinespec.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pod.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/status.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/taskspec.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/validate.go

Add workspace support to colocatedpipelinerun custom task
review them:

[Pipeline-in-pod] workspaces support

---

tekton/publish-customtask.yaml

This comment is likely no longer accurate.
review them:
- n/a Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

Remove stale comment on experimental release task

---

.gitignore

Add vscode files to gitignore
review them:
- n/a Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

Add VSCode files to gitignore

---

pipeline/trusted-resources/README.md
pipeline/trusted-resources/config/config-signing-secret-path.yaml
pipeline/trusted-resources/pkg/config/config.go
pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go

Add  optional config for skip TaskRun verification in trusted TaskRun to let the user
determine  verification.
Fix: #870 
review them:

[pipeline/trusted-resources]Add config option to skip TaskRun verification

---

CONTRIBUTING.md
README.md

This commit clarifies the expectations that contributors and users
can have for code in this repo. Projects are encouraged
to define their own expectations, but in general, expectations are
lower than for other repos in the tektoncd org.
review them:
- n/a Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]

Add details on (lack of) code standards in experimental

---

notifiers/github-app/OWNERS
pipelines-in-pipelines/OWNERS

User @sbwsg has deleted his account.
review them:

[pipelines] [notifiers] Remove @sbwsg -- account deleted.

---

test/presubmit-tests.sh
workflows/go.mod
workflows/pkg/apis/workflows/v1alpha1/workflow_types_test.go

This commit adds workflows to presubmit tests and fixes build errors.
review them:

[workflows] Add presubmit tests

---

workflows/OWNERS

I'm going to be developing on this project and would like to be able to review code in this directory.
review them:

[workflows] Add lbernick to owners

---

concurrency/CONTRIBUTING.md
concurrency/README.md
concurrency/tekton/README.md

This commit adds a link to the concurrency nightly release, plus information for users of and contributors to this project.
review them:

[concurrency] Add installation instructions

---

workflows/config/rbac.yaml
workflows/config/workflows-el.yaml
workflows/go.mod
workflows/minimal.yaml
workflows/pkg/apis/workflows/v1alpha1/workflow_types.go
workflows/pkg/convert/convert.go
workflows/pkg/convert/convert_test.go

Also adds an example file and a cluster wide eventlistener that matches
triggers created by workflows.
review them:

[workflows] Add function to convert workflow to tekton triggers

---

concurrency/OWNERS

Add @jerop to OWNERS
review them:
- n/a Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

[concurrency] Add jerop to OWNERS

---

concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go

This commit adds more logs for the concurrency controller, and exports + tests the Match function.
review them:

[concurrency] Add logs, tests, and comments

---

wait-task/tekton/publish.yaml
wait-task/tekton/release-pipeline.yaml

Pin images used for the wait-task release pipeline

---

tekton/customtask-release-pipeline.yaml
tekton/publish-customtask.yaml

This is used by the following experimental projects:
- concurrency
- pipeline-in-pod
- workflows
/kind misc
review them:

Pin images used for the common release pipeline

---

task-loops/tekton/publish.yaml
task-loops/tekton/release-pipeline.yaml

Pin images used for the task-loops release pipeline

---

pipelines-in-pipelines/tekton/publish.yaml
pipelines-in-pipelines/tekton/release-pipeline.yaml

Pin images used in the pipeline-in-pipelines release pipeline

---

pipeline-to-taskrun/tekton/publish.yaml
pipeline-to-taskrun/tekton/release-pipeline.yaml

Pin images used in the pipeline-to-taskrun release pipeline

---

cel/tekton/publish.yaml
cel/tekton/release-pipeline.yaml

Pin images used for the cel release pipeline
