OWNERS

This will allow community owners to approve PRs in addition to local
OWNERS. This is especially useful in case of moving folders.
cc @bobcatfish @abayer 
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

Add root OWNERS file (from community)

---

webhooks-extension/cmd/extension/README.md
webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/sink-kservice.yaml
webhooks-extension/endpoints/sink.go
webhooks-extension/endpoints/types.go
webhooks-extension/endpoints/webhook.go
webhooks-extension/endpoints/webhook_test.go

This change allows the specification of dockerregistry on the REST endpoint for
creating the webhook. The default value that would otherwise be assigned is that of the environment variable.
review them:

Ability to override the env variable for the target docker registry

---

webhooks-extension/Gopkg.lock
webhooks-extension/README.md
webhooks-extension/cmd/extension/README.md
webhooks-extension/endpoints/sink.go
webhooks-extension/endpoints/types.go
webhooks-extension/endpoints/webhook.go
webhooks-extension/endpoints/webhook_test.go

For our webhook extension we should be able to support Helm pipelines too. This gets us a step closer by being able to do helm upgrades. 
The behaviour before this PR is that we generate Pipeline parameters which includes a release name that is passed into a Helm pipeline. The release name is built up of both the repository name and the short commit ID.
This means that subsequent commits result in entirely new Helm releases instead of upgrading the existing Helm release: because the names differ.
In this PR I've added a new optional field, `releasename`, with character length validation as Helm releases have a maximum length.
I've added a test for such validation, documented that it's a new field one can use, and tested it with a Helm pipeline and deploy task (I want to contribute said …

Add releasename as optional param (used with Helm pipeline)

---

webhooks-extension/README.md
webhooks-extension/cmd/extension/README.md
webhooks-extension/config/extension-service.yaml
webhooks-extension/endpoints/shared-test-funcs.go
webhooks-extension/endpoints/types.go
webhooks-extension/endpoints/webhook.go
webhooks-extension/endpoints/webhook_test.go

This commit adds an endpoint such that default settings can be
retrieved to be later displayed in UI panels.  A struct is stored
against the Resource and is configured with values at creation of
the Resource.  Additionally, there is a minor change to the url path.
review them:

Change extension annotation and add endpoint to get default env settings

---

webhooks-extension/test/install_prereqs.sh
webhooks-extension/test/util.sh

Resolves "Service Timeout" problems using Docker Desktop (I'm using version 2.0.3.0 edge). By using LoadBalancer, the Istio ingress gateway service in istio-system gives the ip `localhost` and not `none` like NodePort does.
I know https://knative.dev/docs/install/knative-with-docker-for-mac/ mentions using NodePort but I also know it reliably doesn't work and this does...
review them:

Use LoadBalancer not NodePort for Istio and Knative

---

webhooks-extension/cmd/extension/Dockerfile_test
webhooks-extension/cmd/extension/README.md
webhooks-extension/cmd/extension/main.go
webhooks-extension/cmd/sink/Dockerfile_test
webhooks-extension/endpoints/webhook.go
webhooks-extension/endpoints/webhook_test.go

Adds the ability to delete webhooks by name and if &deletepipelineruns=true is set, delete the PipelineRuns that are for the same Git repository URL. This is only going to work for PipelineRuns we create through the extension as we label them. These labels are what I use to do the comparison with.
I've also made the images Alpine to reduce their size (for our tests Dockerfiles), added tests and API docs.
review them:

Add delete endpoint for webhooks, optionally deleting PipelineRuns

---

tekton-listener/Gopkg.lock

The listener builds fine when `ko apply` is used but local builds were broken due to this needing a `dep ensure`. Im not sure how `ko` was building fine but not locally, Id expect both would fail.
Im not sure the use-case for running the listener locally outside k8s, but it should still build correctly.
```
tekton-listener (oopsforgotdepensure) $ go build ./cmd/...
tekton-listener (oopsforgotdepensure) $ echo $?
0
```
review them:

listener needed a dep ensure

---

webhooks-extension/cmd/extension/README.md
webhooks-extension/endpoints/credentials.go
webhooks-extension/endpoints/credentials_test.go
webhooks-extension/endpoints/webhook.go
webhooks-extension/pkg/utils/utils.go

As part of https://github.com/tektoncd/dashboard/issues/160 I'm moving support for secrets that are access tokens out of dashboard into webhooks-extension. This PR adds the support to webhooks extension. A second PR will prune down credentials.go in dashboard. 
review them:
- [] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

REST API for accesstokens

---

tekton-listener/cmd/tekton-listener/main.go
tekton-listener/pkg/reconciler/tektonlistener/reconciler_test.go
tekton-listener/test/presubmit-tests.sh
test/presubmit-tests.sh
vendor/github.com/tektoncd/plumbing/LICENSE
vendor/github.com/tektoncd/plumbing/scripts/README.md
vendor/github.com/tektoncd/plumbing/scripts/dummy.go
vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
vendor/github.com/tektoncd/plumbing/scripts/library.sh
vendor/github.com/tektoncd/plumbing/scripts/markdown-link-check-config.rc
vendor/github.com/tektoncd/plumbing/scripts/markdown-lint-config.rc
vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
webhooks-extension/pkg/utils/utils_test.go
webhooks-extension/test/presubmit-tests.sh

Tests will run for all PRs, but it should run only the folder that
have changed files. If files are changed accross folders, it will run
all of the tests.
Fixes #59 although, we'll need to add actual integration tests function
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
review them:

enable presubmit tests on experimental repository

---

webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

If a user supplies a repository URL that ends with .git the sink will
not find a match for the actual webhook.  The actual webhook's payload
does not have the .git suffix and so does not match the one stored in
the config map.
When examining the config map to retrieve the settings needed to create the pipeline run, we now ignore the case and the .git suffix when comparing the repo URL.
review them:
- [N/A ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Fix issue with user supplying repo with .git suffix

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js

Problem was caused because on creation of the new secret, the modal was toggled to no longer be shown and as part of that function, the 'newSecretName' was reset to ''.  The subsequent action to then set 'gitsecret' in state, simply set the value to '' and thus it was not shown as the 'selectedItem'.
This change removes the reset of the 'newSecretName' during toggling of the modal.  We do not need to worry about the name being shown again if the user subsequently clicked on the plus icon, as this 'newSecretName' is set to '' after 'gitsecret' has been set in state, after the modal is toggled.
review them:
- [ N/A ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if …

Fix issue with secret creation not auto selected (issue #80)

---

tekton-listener/test/publish-images.sh
test/publish-images.sh
webhooks-extension/test/publish-images.sh

It will call all project's `publish-images.sh` script.
- tekton-listener publishes `controller` and `tekton-listener` images
- webhooks-extension publishes `sink` and `extension` images
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
/cc @iancoffey @mnuttall @bobcatfish 
Companion PR is https://github.com/tektoncd/plumbing/pull/40
review them:
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Add script to publish experimental images

---

test/publish-images.sh

Let's make sure we are targeting the right path using `dirname` and
absolute path.
I am so sorry :bowing_man: :man_facepalming: 
/cc @mnuttall 
review them:
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

publish-images.sh: use the real correct path to call sub scripts 🤕

---

webhooks-extension/DEVELOPMENT.md
webhooks-extension/README.md
webhooks-extension/cmd/extension/Dockerfile
webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/scripts/install_istio.sh
webhooks-extension/scripts/install_knative.sh
webhooks-extension/test/README.md

Update the README for the webhooks extension with trivial install instructions for users to get started quickly, additionally add simplified scripts to a /scripts directory. Add a fix in the Go code for the extension to allow for docker build only method over Ko
review them:

Update README with quickstart install instructions

---

webhooks-extension/cmd/extension/README.md
webhooks-extension/test/cleanup.sh
webhooks-extension/test/config.sh
webhooks-extension/test/setup_webhook_simple_test.sh

For https://github.com/tektoncd/experimental/issues/104. Actually our API docs didn't mention the namespace being default much, so I've looked for places in our test scripts that use `default` and a `default` service account still. Let's see if this works. This also changes the ServiceAccount to be tekton-dashboard for tests.
review them:

Use tekton-pipelines as namespace for test scripts and docs

---

webhooks-extension/config/sink-kservice.yaml

The default install namespace for the dashboard is now tekton-pipelines, however the config/sink-kservice.yaml lists the INSTALLED_NAMESPACE env var as "default".  This PR corrects this.
review them:
- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Correct default install namespace to tekton-pipelines

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalSecretName.test.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

issue: #66 
#Changes
Fixed the tab indexing by initializing all the values to 0 & leaving the browser do the logical ordering and surprisinly works. But its worth mentioning that I had to cheat a little with plain javascript when trying to skip the disabled components because for some reason their child elements still had `tabIndex set to 0` and was interrupting the order. I also changed the tooltips to "hoverable" ones but only to those that are in the main page and not the modals because for some reason they were not being outputted correctly. Lastly, I had to update the test with some errors regarding the `window.toScroll` & create a new test file to bypass the `'initialFocus' did not return a node` error.  …

fix tab indexing & replace tooltips to hoverable ones

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.js
webhooks-extension/src/WebhookApp.test.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js

issue: #102 
shows a notification in create webhook component when the last webhook was deleted from the webhook table component. This was possible by declaring a state in the parent container, WebhookApp, & passed to both child components, WebhookCreate & WebhookDisplayTable, where when the last webhook is deleted in the table component, this variable's state is changed and when the app changes to the create form component, the variable is noticed and consequently shows the notification message. 
Lastly, the were some test updates done & added one to test this behavior in the parent component.  
review them:

show notification when the last webhook deleted

---

webhooks-extension/package-lock.json
webhooks-extension/pkg/endpoints/sink.go

For https://github.com/tektoncd/experimental/issues/140
Adds gitBranch label to PipelineRuns created through webhooks, using the `Ref` field and string extraction
```
adams-mbp:dashboard aroberts$ k get pipelinerun -o yaml
apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
creationTimestamp: 2019-07-11T15:18:09Z
generation: 1
labels:
app: tekton-webhook-handler
gitBranch: master
gitOrg: aroberts
gitRepo: icp-nodejs-sample
gitServer: github.ibm.com
````
review them:

Add branch to pipelinerun label from webhooks

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js

Switched the current loading spinner to the data table skeleton when the page is loading & updated the necessary test case.

data table skeleton when in loading state

---

webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml

Add a role, binding and service account for use by the webhooks extension.
I've not tested this yet with knative creating a PipelineRun but here's the (admittedly brief, I didn't change much actually!) progress so far.
review them:

Add webhooks extension role, binding and SA

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/pkg/endpoints/credentials.go
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/src/api/index.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

This change modifies the webhook create panel to add clarity around
the values being provided.  It also ensures the secret selection
for the secret containing the access token is never disabled or
dependant on the namespace.
The changes in the runtime allow pipelineruns to be created in a
specified namespace and ensure all lookups occur in a single
configmap hosted in the install namespace.
review them:
- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Multi-Namespace support for webhook pipelines

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

issue: #151 
A bug with the inline notification component where after closing it the first time, was remaining hidden  when more errors occurred afterwards. Adding a handler to set the `showNotification` state  to `false` every time it was dismissed fixed the problem.

fix bug where after closing initial notification, the next ones were not appearing

---

webhooks-extension/DEVELOPMENT.md
webhooks-extension/test/README.md
webhooks-extension/test/util.sh

Changed the docs to recommend 'npm ci' instead of 'npm install' and to recommend version 10 of node.js
review them:

Replace 'npm install' with 'npm ci' for installing webhooks-extension

---

webhooks-extension/pkg/endpoints/credentials_test.go
webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/test/presubmit-tests.sh

The unittest run was previously returning the result of the echo command rather than returning the result of the unittests.  I've added in a local variable to store this result and return it.
review them:

Fix PR unittest status by returning the result of the tests not an echo

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

issue: #150 
For some weird case the hoverable tooltips when clicked were POSTing the create webhook form. Tried numerous approaches but the one that worked the most was adding a onClickHandler that fires a the preventDefault function.

prevent tooltips from posting form

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.js
webhooks-extension/src/WebhookApp.test.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalSecretName.test.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

issue: #137 
removed & replaced the api calls for getting namespaces, service accounts and pipelines with the redux selectors & actions that were passed as props to the extension component. Also updated all necessary tests. 
Its worth mentioning that the api call to get webhook secrets was left because at the moment the getSecrets action did not return the secrets created for webhooks.

replace api calls with dashboard's redux selectors & actions

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.js
webhooks-extension/src/WebhookApp.test.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalSecretName.test.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

issue: #137 
removed & replaced the api calls for getting namespaces, service accounts and pipelines with the redux selectors & actions that were passed as props to the extension component. Also updated all necessary tests. 
Its worth mentioning that the api call to get webhook secrets was left because at the moment the getSecrets action did not return the secrets created for webhooks.

replace pipelines api call with dashboard's redux selectors & actions

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

issue: #64 
Added input validation for text inputs in the web hook create page. For some fields they are validated to be k8s resources while others check if they are not blank. Finally, added two test cases verifying the expected behavior.

input validation when creating a webhook

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.js
webhooks-extension/src/WebhookApp.test.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalSecretName.test.js
webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js

removed & replaced the api calls for getting namespaces, service accounts and pipelines with the redux selectors & actions that were passed as props to the extension component. Also updated all necessary tests.
Its worth mentioning that the api call to get webhook secrets was left because at the moment the getSecrets action did not return the secrets created for webhooks.

replace service accounts api call with dashboard's redux selectors & actions

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

issue: #170 
the warning message was removed when the lifecycle method getDerivedStateFromProps was added with the lines that were changing state in the render method.

remove warning message when setting state in render method

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js

issue: #186 
Changed the component to use Carbon Design's password text input which ultimately ended up not using declared state variables & handlers. Added some padding to the content modal so the tooltip text (appears when password icon is hovered) can be seen. Lastly, updated test case.

align show password icon with invalid icon in access token text input

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/src/api/index.js

issue: #192 
The approach I did was basically to search & remove the keyword `create` that was is not supposed to be present in the api uri call.

fix 404 error when refreshing create webhook page

---

webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/task-monitor-result.yaml
webhooks-extension/pkg/endpoints/sink.go

The status table added to the pull request after pipelineruns have completed, includes a link to the pipelinerun from the table.  On openshift this link does not appear to be obtaining the correct route - this change uses the internal dashboard service rather than the https dashboard service to exploit using the endpoint REST endpoint to get the correct external route to the dashboard.
review them:

Use correct PipelineRun URL in status table for OpenShift

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js

For https://github.com/tektoncd/experimental/issues/201
Tested with two webhooks with 10 PipelineRuns each on a pretty slow OpenShift on Fyre cluster
I realise this isn't exactly massive scale so perhaps we need to come up with a better solution eventually (@dibbles has noticed retrieving pipelines being very slow too for a given namespace, so I think we need to improve our "slow system" handling as part of a larger item)
Either way, this gets us past the current problem where 500 ms is definitely too short a timeout period, and because of the refresh and warning, users will see that even if a timeout does occur (for testing I set it to 1 ms so I'd always see the notification), a notification occurs and the table is refreshed anyway incase it really was deleted.
These are the criteria …

Increase delete webhook timeout to 5s, display warning if timeout, refresh page

---

webhooks-extension/pkg/endpoints/sink.go

Issue #226 
Issue #226 
Changes
The pull request pipeline resource appears to want the HTMLURL from the
GitHub webhooks payload, otherwise the string manipulation fails to find
the pull request number.  Changed the sink to use 
`webhookData.PullRequest.HTMLURL` rather than the current
`strings.Replace(webhookData.PullRequest.URL, "api/v3/repos/", "", 1)`
Additionally, the way the branch name is obtained in the sink needs to
differ between push and pull_request events as the payloads are different.
In the case of the pull_request event we no longer send the ref through
`extractBranchFromRef` and the method itself has been renamed to 
`extractBranchFromPushEventRef`
review them:
- [n/a ] Includes …

Change data used from webhook payload in pipelineresources

---

webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/task-monitor-result.yaml

Changes
Issue #233 
Added `type: string` to input params of the monitor task.
review them:

Add types to params on the monitor task

---

webhooks-extension/config/triggers_prototype/README.md
webhooks-extension/config/triggers_prototype/test/webhook-run.yaml
webhooks-extension/config/triggers_prototype/webhook.yaml

Tested this with github.com and github.ibm.com using PATs and secrets created through the Tekton Dashboard's Webhook Extension.
This is for https://github.com/tektoncd/experimental/issues/241
Credits to @akihikokuroda for the create webhook work this is largely based on 😄 
review them:

Add Tekton Task and TaskRun to create and delete GitHub webhooks

---

webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/triggers_prototype/README.md
webhooks-extension/config/triggers_prototype/route.yaml
webhooks-extension/config/triggers_prototype/test/route-run.yaml

For https://github.com/tektoncd/experimental/issues/278
Example:
```
[root@requite1 triggers_prototype]# k logs route-run-r7mrh-pod-45cbdd 
Creating the Route
route.route.openshift.io/listener created
[root@requite1 triggers_prototype]# k get route
NAME               HOST/PORT                                                 PATH      SERVICES           PORT      TERMINATION          WILDCARD
listener           listener-tekton-pipelines.thehostname                     listener           <all>     reencrypt/Redirect   None
tekton-dashboard   tekton-dashboard-tekton-pipelines.thehostname             tekton-dashboard   <all>     reencrypt/Redirect   None
```
RBAC augmented too
review them: …

Add Tekton Task and TaskRun to create and delete Routes

---

webhooks-extension/config/task-monitor-result.yaml
webhooks-extension/pkg/endpoints/sink.go
webhooks-extension/pkg/endpoints/types.go

`PipelineResources` were internally modified, which broke the task monitor on Tekton 0.7 (as well as 0.8). This adds a copy step so that the pull-request resource properly uploads when used within the task monitor
review them:

Fix task monitor by adding copy step

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

Fixes #266
The `WebhookApp` was taking its state directly from the Redux store using
the Dashboard's selected namespace (`getSelectedNamespace()`). Instead, we
want to use `ALL_NAMESPACES` so that the `WebhookApp`'s state does not
change when the Dashboard's selected namespace changes.
Also, this PR adds an empty state to the Pipeline and ServiceAccount dropdowns.
review them:

Use ALL_NAMESPACES for webhooks-extension state

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/src/WebhookApp.js
webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
webhooks-extension/src/components/WebhookBranches/WebhookBranches.scss
webhooks-extension/src/components/WebhookBranches/index.js
webhooks-extension/src/components/WebhookBranches/tests/WebhookBranches.test.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js

as per epic #37, issues #48 & #50  are implemented in this PR
In the `WebhookDisplayTable` container I added a "passive" modal component that will display the branches within a simple sortable table. It uses the GitHub API to fetch the branches & saves the data in the component's state rather than the redux store. Lastly, I added the necessary test cases as well.
review them:

View Branches when Webhook Clicked

---

webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js

issue: #211 
- Other delete modals: 
_Webhooks_
_Secrets_
- Access Token Modals:
_Before_
_After_

Consistent Modal Buttons

---

webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss

With PR #300 merged, the styles for the disabled create button got lost. This PR should have it back to normal.

Webhook Create Button Style Update

---

webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss

issue: #130 
Apparently the bug was fixed when the `border-collapse` property was removed. 
*This change doesn't affect the page when viewed in Safari or Chrome*

Border Correction for Firefox

---

webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

For: https://github.com/tektoncd/experimental/issues/314
One character change so that webhook names can include "0".
review them:

Webhook names can contain '0'

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js

issue: #271 
The input element for the secret name was missing the `invalid` property. Added that, a test case & also changed the approach when disabling & enabling the `create` button in the modal.

Validating Secret in Webhook Create Page

---

webhooks-extension/test/publish-images.sh

Should result in the interceptor image being built and published, thus available in our published builds.

Use interceptor folder for nightly builds

---

webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/monitor.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/docs/CustomizingTheMonitor.md
webhooks-extension/docs/Monitoring.md
webhooks-extension/pkg/endpoints/types.go
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

This PR is for https://github.com/tektoncd/experimental/issues/220
make monitor task timeout message configureable
```
- name: commenttimeout
description: The text of the timeout comment
default: "Unknown"
```
review them:

make monitor task timeout message configureable

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/src/WebhookApp.test.js
webhooks-extension/src/api/index.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js

issue: #268 
Tried a couple of approaches, but mapping each promise by itself & then calling `Promise.all` seemed to worked the best.
Bonus:
I also made the table unselect the rows `when` the delete modal appears. Which means that if the user decides to cancel the delete call, the modal disappears and the page will look like it was refreshed. Let me know how you feel about this.
review them:

Remove Successfully Deleted Webhooks when Attempting to Delete Multiples

---

webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/monitor.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml

This PR is for https://github.com/tektoncd/experimental/issues/334
The `.MANIFEST` files in the `labels` and `comments` directories are copied into the directories under `output` directory for the pullrequest pipeline resource.
review them:

copy original .manifest files to output directory for pipeline 0.8

---

webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/monitor.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml

To work with both v0.7 and v0.8 of pipelines, an additional if statement has been added to only copy the /workspace/pull-request/comments/.MANIFEST file if it exists. (Fixes Issue #363)
review them:

Issue #363: Fix "No such file or directory" error for the .MANIFEST file during monitor

---

webhooks-extension/config/extension-service.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

For Kabanero Issue: https://github.com/kabanero-io/kabanero-foundation/issues/135
Restricts webhook names to be no more than 57 characters (or 63 including the name extension).
review them:

Adds correct validation for webhook name length

---

webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

Issue 332: Removal of the configmap in favor of using the data as stored in the eventlistener's triggers.
review them:

Remove the ConfigMap for webhooks

---

webhooks-extension/cmd/interceptor/interceptor.go
webhooks-extension/cmd/interceptor/interceptor_test.go

For #375
Changed the interceptor to unmarshal the push event webhook payload into a go-github PushEvent rather than the incorrect WebhookPayload.
This now avoids the error: cannot unmarshal string into Go struct field Repository.organization of type github.Organization
review them:
- [] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Issue 375: Fix for org repositories not triggering pipelineruns

---

webhooks-extension/cmd/interceptor/interceptor.go
webhooks-extension/cmd/interceptor/interceptor_test.go
webhooks-extension/docs/Parameters.md

Issue 377: This change adds a new property into the webhook body
payload by the interceptor.  The new property is
"webhooks-tekton-image-tag" and can be used in the trigger
bindings file(s).
If the push of a git tag causes the webhook to trigger, this property
will be set to the value/label of the tag.  In other cases, the
property is set to the short commit id.
review them:

Add a suggested image tag to the webhook event payload

---

webhooks-extension/config/extension-deployment.yaml
webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml

Updated the ClusterRole for the non-openShift deployments so that they have the same
access to Tekton resources as the openshift ClusterRole.
Thanks for finding this @akihikokuroda 🙂 
/cc @a-roberts 
/cc @mnuttall 
review them:

Add Triggers to the webhooks ClusterRole

---

webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
webhooks-extension/config/monitor.yaml
webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml

For: https://github.com/tektoncd/experimental/issues/388
Fixes issue with monitor task not picking up the correct service account name by changing from serviceAccount to serviceAccountName and updating the RBAC to have the correct functionality for PipelineRuns.
review them:

Fix service account name picked up by monitor task

---

webhooks-extension/base/400-monitor-task.yaml

For https://github.com/tektoncd/experimental/issues/404
All previous comments were deleted (noticed when you refreshed the page) with our monitor task. This change fixes said problem.
review them:

Preserve existing comments for monitor task

---

webhooks-extension/base/400-monitor-task.yaml
webhooks-extension/base/400-monitor-triggertemplate.yaml
webhooks-extension/docs/CustomizingTheMonitor.md
webhooks-extension/pkg/endpoints/types.go
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

For https://github.com/tektoncd/experimental/issues/395
Also adds override for the missing comment
Testing is:
- reopen two PullRequests thus triggering two PipelineRuns
- delete one PipelineRun, check table reflects state accordingly
Also:
- reopen two PullRequests thus triggering two PipelineRuns
- delete both PipelineRuns, check table reflects state accordingly

Handle missing PipelineRuns for monitor task

---

webhooks-extension/base/300-extension-service.yaml
webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js

For: https://github.com/tektoncd/experimental/issues/389
- Adds a service account column to the webhooks table and updates the corresponding test for this display
- Adds the service account to the modal view of a single webhook
review them:

Add service account column to webhooks display table

---

webhooks-extension/docs/Uninstall.md

For https://github.com/tektoncd/experimental/issues/441
Verified deleting a CRD (e.g. when you delete Triggers) it does delete any created reosurces too, e.g
```
(base) adams-mbp:dashboard aroberts$ k get el
NAME                            AGE
tekton-webhooks-eventlistener   6d22h
(base) adams-mbp:dashboard aroberts$ k get crd | grep eventlistener
eventlisteners.tekton.dev                                   2020-01-21T13:36:51Z
(base) adams-mbp:dashboard aroberts$ k delete crd eventlisteners.tekton.dev
customresourcedefinition.apiextensions.k8s.io "eventlisteners.tekton.dev" deleted
(base) adams-mbp:dashboard aroberts$ k get el
Error from server (NotFound): Unable to list "tekton.dev/v1alpha1, Resource=eventlisteners": the server could not find the requested resource (get …
```

Update uninstall docs to include created route/ingress

---

webhooks-extension/Gopkg.lock
webhooks-extension/Gopkg.toml
webhooks-extension/base/200-clusterrole-eventListener.yaml
webhooks-extension/cmd/interceptor/interceptor.go
webhooks-extension/cmd/interceptor/utils_test.go
webhooks-extension/docs/InstallPrereqs.md
webhooks-extension/pkg/endpoints/credentials.go
webhooks-extension/pkg/endpoints/shared-test-funcs.go
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/pkg/utils/utils.go

Modifies eventlistener to triggers 0.2.1 format.  This is possibly a breaking change and I believe users of previous versions will need to remove all existing webhooks before upgrading to triggers 0.2.1 and this PR level of the webhooks extension. 
review them:

Updates webhooks extension eventlistener to be compatible with triggers 0.2.1

---

webhooks-extension/Gopkg.lock
webhooks-extension/docs/InstallNightlyBuild.md
webhooks-extension/docs/InstallReleaseBuild.md
webhooks-extension/pkg/endpoints/webhook.go

This PR for https://github.com/tektoncd/experimental/issues/279
when the callback URL has "https" protocol.
The name of the TLS certificate secret can be specified in WEBHOOK_TLS_CERTIFICATE
environment variable.  The default is "cert-" + eventlistener name.
When the secret doesn't exit with the name, the new certificate secret
is created and the certificate is signed by the framework.
review them:

TLS certificate is added to the ingress for the eventlistener

---

oci/go.mod
oci/pkg/action/pull.go
oci/pkg/action/push.go
oci/pkg/oci/image.go

@sthaha @pierretasci
Instead of parsing image ref strings ourselves, use go-containerregistry which has extensive support and tests for image ref parsing.
review them:
- [n] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

Use go-containerregistry to parse image references

---

oci/pkg/oci/bundle.go

A valid yaml that starts with `---` generates a warning as `readPath`
splits the file at `---` and tries to decode the first empty string
which results in a warning.
This patch fixes the issue by ignoring all empty strings (including
those that are just while spaces)
review them:
- [🙅‍♂ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Ignore empty content when decoding

---

webhooks-extension/DEVELOPMENT.md

I think that this is supposed to read `npm run build_ko` instead of `npm
run build`.
/cc @a-roberts 
/cc @dibbles 
review them:

Use npm run build_ko in DEVELOPMENT instructions

---

webhooks-extension/pkg/endpoints/webhook.go

For https://github.com/tektoncd/experimental/issues/488
We were previously returning nil after deleting the Ingress instead of continuing to delete the found TriggerBindings we had created
review them:

Continue when Ingress is deleted so we delete made TriggerBindings

---

webhooks-extension/base/300-extension-service.yaml
webhooks-extension/docs/ManagedEventListener.md
webhooks-extension/package-lock.json
webhooks-extension/package.json
webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go
webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js

For https://github.com/tektoncd/experimental/issues/489
This also fixes over 37,000 low sev vulns (React and Acorn)
Documentation and Go code changes to:
1) Pick up the namespace even if no TriggerBindings are found for a webhook (essential as it's used for the deletion)
2) Assume monitor-task was in use by the webhook, todo should we mention if it's not? Is anyone really using another monitor task? If so then it's tricky because of the assumption it's called `monitor-task` with the Go changes here
3) Avoid the need to modify the EventListener incase an in-use TriggerBinding is accidentally delated
4) Avoid the need to delete the entire EventListener/Ingress to get back to a healthy state
review them:
_See [the …

Handle and provide guidance when TriggerBindings are missing for a webhook

---

helm/OWNERS
helm/README.md
helm/pipeline/Chart.yaml
helm/pipeline/README.md
helm/pipeline/README.md.gotmpl
helm/pipeline/crds/clustertask.yaml
helm/pipeline/crds/condition.yaml
helm/pipeline/crds/image.yaml
helm/pipeline/crds/pipeline.yaml
helm/pipeline/crds/pipelinerun.yaml
helm/pipeline/crds/resource.yaml
helm/pipeline/crds/task.yaml
helm/pipeline/crds/taskrun.yaml
helm/pipeline/templates/NOTES.txt
helm/pipeline/templates/_helpers.tpl
helm/pipeline/templates/clusterrole.yaml
helm/pipeline/templates/clusterrolebinding.yaml
helm/pipeline/templates/configmaps.yaml
helm/pipeline/templates/controller_deployment.yaml
helm/pipeline/templates/controller_service.yaml
helm/pipeline/templates/customresourcedefinitions.yaml
helm/pipeline/templates/podsecuritypolicy.yaml
helm/pipeline/templates/serviceaccount.yaml
helm/pipeline/templates/webhook_admission.yaml
helm/pipeline/templates/webhook_deployment.yaml
helm/pipeline/templates/webhook_poddisruptionbudget.yaml
helm/pipeline/templates/webhook_service.yaml
helm/pipeline/values-production.yaml
helm/pipeline/values.yaml
helm/repo-sync.sh

This PR proposes to add a helm chart for tekton.
This was proposed here https://github.com/tektoncd/plumbing/issues/278.
The helm chart doesn't include dashboard, triggers, or operator. I will make separate charts for them in separate PRs. This one focuses only on pipeline.
The pipeline version used to create the chart is  v0.11.0-rc2. Supporting v0.10 is imho not worth the effort, by the time this chart is released v0.11 will probably be out.
This is work in progress, things not implemented yet :
Feedback welcome, thanks.

Add pipeline helm chart

---

helm/README.md
helm/dashboard/Chart.yaml
helm/dashboard/README.md
helm/dashboard/README.md.gotmpl
helm/dashboard/crds/extension.yaml
helm/dashboard/templates/NOTES.txt
helm/dashboard/templates/_helpers.tpl
helm/dashboard/templates/clusterrole.yaml
helm/dashboard/templates/clusterrolebinding.yaml
helm/dashboard/templates/customresourcedefinitions.yaml
helm/dashboard/templates/dashboard_deployment.yaml
helm/dashboard/templates/dashboard_pipeline.yaml
helm/dashboard/templates/dashboard_service.yaml
helm/dashboard/templates/dashboard_task.yaml
helm/dashboard/templates/serviceaccount.yaml
helm/dashboard/values.yaml
helm/pipeline/README.md
helm/pipeline/README.md.gotmpl

This pull request adds a helm chart for Tekton Dashboard.
It is a follow up from the previous PR #494.
Helm chart support was proposed here: https://github.com/tektoncd/plumbing/issues/278
This is work in progress, remaining TODOs:
Minor issues:
- Namespace `tekton-pipelines` is hardcoded in a few places (see https://github.com/tektoncd/dashboard/pull/1262)
I will try to make the dashboard not dependent of hardcoded namespaces and will update the chart accordingly.

Add dashboard helm chart

---

webhooks-extension/Gopkg.lock
webhooks-extension/Gopkg.toml

Now Triggers 0.4 is a thing we shouldn't be pinning to a release candidate version, tested this morning in a fresh environment and all continues to work fine
toml file changed, dep ensured to give us the new lock file contents
review them:

Use Triggers 0.4 (not a release candidate) in Gopkg yaml

---

helm/.hack/check-helm-docs.sh

This pull request adds a shell script to verify that helm docs are up to date.
This will be used in a prow job to validate helm docs against pull requests.
The related `tektoncd/plumbing` issue is here: https://github.com/tektoncd/plumbing/issues/309

Add script to check helm docs are up to date

---

helm/README.md
helm/triggers/Chart.yaml
helm/triggers/README.md
helm/triggers/README.md.gotmpl
helm/triggers/crds/clustertriggerbinding.yaml
helm/triggers/crds/eventlistener.yaml
helm/triggers/crds/triggerbinding.yaml
helm/triggers/crds/triggertemplate.yaml
helm/triggers/templates/NOTES.txt
helm/triggers/templates/_helpers.tpl
helm/triggers/templates/clusterrole.yaml
helm/triggers/templates/clusterrolebinding.yaml
helm/triggers/templates/configmaps.yaml
helm/triggers/templates/controller_deployment.yaml
helm/triggers/templates/controller_service.yaml
helm/triggers/templates/customresourcedefinitions.yaml
helm/triggers/templates/podsecuritypolicy.yaml
helm/triggers/templates/serviceaccount.yaml
helm/triggers/templates/webhook_admission.yaml
helm/triggers/templates/webhook_deployment.yaml
helm/triggers/templates/webhook_poddisruptionbudget.yaml
helm/triggers/templates/webhook_service.yaml
helm/triggers/values-production.yaml
helm/triggers/values.yaml

This pull request adds a helm chart for Tekton Triggers.
It is a follow up from the previous PRs #494 and #505.
Helm chart support was proposed here: https://github.com/tektoncd/plumbing/issues/278
This is work in progress, remaining TODOs:

Add triggers helm chart

---

helm/README.md
helm/dashboard/Chart.yaml
helm/dashboard/README.md
helm/pipeline/Chart.yaml
helm/pipeline/README.md

Added note about chart versioning.
Made chart versioning consistent for dashboard and pipelines.
Related issue: https://github.com/tektoncd/plumbing/issues/278

Helm charts versioning

---

helm/pipeline/README.md
helm/pipeline/templates/clusterrole.yaml
helm/pipeline/templates/webhook_admission.yaml
helm/pipeline/templates/webhook_secret.yaml
helm/pipeline/values.yaml

This PR updates pipeline chart to `v0.11.3` and fixes a number of issues:
- missing secret for webhook
- webhook names incorrectly templated
- validatingwebhookconfigurations missing rbac
- added example values in configmaps as empty configmaps trigger a log error

Pipeline chart v0.11.3 and fixes

---

webhooks-extension/README.md
webhooks-extension/base/400-monitor-triggertemplate.yaml

Closes https://github.com/tektoncd/experimental/issues/547
Important note: hold on, let's see what we hear regarding https://github.com/tektoncd/triggers/issues/583 as obviously the steps here aren't ideal
review them:

Add Triggers 0.5.0 support for webhooks extension

---

webhooks-extension/base/400-monitor-triggertemplate.yaml

Closes https://github.com/tektoncd/experimental/issues/552
By omitting the namespace for templated resources, they sit in the template's namespace - which is openshift-pipelines on OpenShift, overridden correctly
review them:

Fix wrong namespace for monitor TaskRun on OpenShift

---

webhooks-extension/pkg/endpoints/webhook.go
webhooks-extension/pkg/endpoints/webhook_test.go

This PR is related to the changes in the dashboard here https://github.com/tektoncd/dashboard/pull/1443.
The dashboard service should be available on both k8s and openshift, the secure service is replaced by `tekton-dashboard-proxy` and the openshift `Route` points to the proxy.
review them:

[Webhooks] Always use Dashboard service

---

generators/cmd/cli/cmd/root.go
generators/cmd/cli/cmd/show.go
generators/cmd/cli/cmd/write.go
generators/cmd/main.go
generators/go.mod
generators/go.sum
generators/pkg/generator/generate.go
generators/pkg/generator/generate_test.go
generators/pkg/parser/parser.go
generators/pkg/parser/parser_test.go
generators/pkg/parser/testdata/spec-full.yaml
generators/pkg/parser/testdata/spec.yaml
generators/pkg/writer/testdata/spec.yaml
generators/pkg/writer/testdata/task.yaml
generators/pkg/writer/write.go
generators/pkg/writer/write_test.go

I am working on [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590).
This project aims at generating Tekton spec from simplified configs, which will help users bootstrap pipelines in a configurable way. 
I want to make some changes to this project:
1. To help users interact with generators, add the CLI command `show` to it.
2. Add support for writing output to disk. 
review them:

Add CLI and Write support to Tekton Generators

---

results/cmd/api/main.go
results/cmd/api/main_test.go
results/cmd/watcher/main.go
results/go.mod
results/go.sum

This pull request is to implement a UpdateTaskRun() function to receive update request from users and update taskruns 
in the database.
1. Currently, we use kubernetes UUID as key to update, we will use server generated results_id soon.
2. Due to lack of FieldMaskUtil API, right now we are updating whole taskrun instead of selected fields, may add this future in the future once we have the API
These are the criteria that every PR should meet, please check them off as cyou
review them:

Update task version 1

---

results/cmd/api/main.go
results/cmd/api/main_test.go
results/cmd/watcher/main.go
results/go.mod
results/proto/api.proto
results/proto/proto/api.pb.go

Added a new message TaskRunResult to combine TaskRun and results_id
Modified CRUD to make them now query based on results_id
Generate a random unique results_id inside CreateTaskRunResult
Modified tests to be compatible with new function interfaces
review them:

Implement adding results_id to schema v1

---

generators/cmd/cli/cmd/root.go
generators/pkg/manager/manage.go
generators/pkg/manager/manage_test.go

This PR aims to add support for managing generated configs on Kubernetes cluster for [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590).
The changes includes:
1. Add support for applying config to cluster.
2. Add support for deleting configs from cluster.
review them:

Add support for applying and deleting configs on cluster

---

generators/cmd/cli/cmd/apply.go
generators/cmd/cli/cmd/delete.go

This PR aims to add support for [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590) cli.
The changes include:
1. Add the sub-command `apply` to apply the generated resources on the cluster.
2. Add the sub-command `delete` to delete the generated resources on the cluster.
review them:

Add apply and delete sub-commands to generators cli

---

hub/ui/package.json
hub/ui/src/components/footer/Footer.tsx
hub/ui/src/components/search-bar/SearchBar.tsx

Previously, a user was able to search a resource by `name` only.
This patch will allow User to search a resource by both `name` and `displayName`.
review them:

Hub: fixes search

---

generators/README.md
generators/go.mod
generators/go.sum
generators/pkg/generator/generate.go
generators/pkg/generator/generate_test.go
generators/pkg/generator/testdata/eventlistener.yaml
generators/pkg/generator/testdata/pipeline.yaml
generators/pkg/generator/testdata/triggerbinding-pr.yaml
generators/pkg/parser/parser_test.go
generators/pkg/parser/testdata/spec-full.yaml
generators/pkg/writer/testdata/config.yaml
generators/pkg/writer/testdata/spec-full.yaml
generators/pkg/writer/testdata/spec.yaml
generators/pkg/writer/write.go

This PR aims to add more fields to the input Github config settings tohelp user specify their workflow with more flexibilty for [Tekton Generators](https://github.com/tektoncd/pipeline/issues/2590).
The changes includes:
1. Add fields `branch`, `storage`, `secretName`, `secretKey`, `serviceAccountName` to the `GitHubSpec` structure.
2. Add CEL in the triggers to specify the branch.
review them:

Update the GitHub Config settings for Generators

---

hub/api/pkg/git/repo.go

Previously, sync service used to read-only tasks from catalog.
Now, it will read the task and pipeline from the catalog and add to DB.
review them:

Hub: Add support for pipeline in sync service

---

hub/ui-new/.eslintrc
hub/ui-new/src/components/basic-detail/BasicDetail.tsx
hub/ui-new/src/components/filter/Filter.tsx
hub/ui-new/src/components/task/Task.tsx
hub/ui/src/components/basic-detail/BasicDetail.tsx
hub/ui/src/components/filter/Filter.tsx
hub/ui/src/components/task/Task.tsx

this patch includes
- tooltip for resource type and support tier badge in resource card.
- `courier` and `monospace` font for resource name.
- limits on number of tags in resource card.
review them:

Hub: adds tooltip for badges and font for resource name

---

hub/ui-new/src/components/main/App.tsx
hub/ui/src/components/main/App.tsx

Previously,on clicking resource card it's detail page
was open with scroll position at bottom and showed no content.
Now,detail page opens with scroll position at top.
review them:

Hub: fixes scroll position

---

hub/api/pkg/db/model/20200731_add_modifiedat_to_resource_version.go
hub/api/pkg/db/model/migration.go
hub/api/pkg/db/model/models.go
hub/api/pkg/git/git.go
hub/api/pkg/git/repo.go
hub/api/pkg/service/resource.go
hub/api/pkg/sync/sync.go

Previously, API sync service used to use update_at time to infer the
date a resource was last modified. The sync service also used to parse
the entire catalog if requested even if it was already parsed and
updated in DB.
This patch fixes it by exiting early if the SHA/HEAD of the catalog last
scanned is the same. It also adds a modified_at field to compute and
store the last modified time of the resource instead of relying on the
updated_at so that even if the catalog gets updated, the modified_at
still remains the same.
review them:
- [🙅  ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
_See [the …

Fix resource modified time

---

hub/api/pkg/app/app.go

This adds a sugared logger for gorm log which would be easy to filter
and monitor hub API usage.
review them:

Hub: replace default logger in gorm with suggared logger

---

hub/api/config/12-db-deployment.yaml

Previously Hub db image used postgres:13 which used to get updated
frequently and caused db to fail with the following error
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
[1] FATAL:   database files are incompatible with server
[1] DETAIL:  The database cluster was initialized with CATALOG_VERSION_NO 202005171, but the server was compiled with CATALOG_VERSION_NO 202007201.
[1] HINT:    It looks like you need to initdb.
[1] LOG:     database system is shut down
```
This used to happen because the docker image used to get updated
frequently and overwrote the same tag.
Hopefully pinning down the image using its SHA should fix this 🤞.
These are the criteria that every PR should meet, please check them …

Hub: use sha256 instead of tags

---

hub/ui/src/components/rating/Rating.tsx

This fixes console error, api should be called only if the user is
authenticated, before this it was getting called every time details
page is visited.
review them:
- [🙅  ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

Hub: Fix console error for rating API

---

pipeline/cleanup/README.md
pipeline/cleanup/binding.yaml
pipeline/cleanup/cleanup-template.yaml
pipeline/cleanup/cronjob.yaml
pipeline/cleanup/eventlistener.yaml
pipeline/cleanup/serviceaccount.yaml

This PR fixes #479 by providing documentation on how to use a CronJob to clean up old TaskRuns / PipelineRuns. It is based on what @afrittoli implemented in [tektoncd/plumbing#442](https://github.com/tektoncd/plumbing/pull/442).
review them:

Using CronJobs to automatically clean up completed Runs

---

OWNERS

Add Jason Hall and Andrea Frittoli to the root OWNERS file for
experimental so that the whole governance team is in there.
Removing Mark Nuttall as well since he's OWNER in the
webhooks-extension project already and he's not working on
the other projects in experimental.
review them:

Add Jason and Andrea to owners

---

oci/Makefile

The OCI tool makefile attempts to use the vendor folder for the
build, but there is not vendor folder, so removing that.
review them:

[OCI] Drop the vendor mode in the OCI tool makefile

---

commit-status-tracker/README.md
commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller_test.go
commit-status-tracker/pkg/controller/pipelinerun/secret.go
commit-status-tracker/pkg/controller/pipelinerun/secret_test.go

Support configurable secret names.
This allows configuring the name of the secret to use to authenticate requests.
By providing an environment variable `STATUS_TRACKER_SECRET` with the name of a secret, you can override the
default `commit-status-tracker-git-secret` value with a secret name of your choice.
review them:

Support configurable secret names.

---

results/README.md
results/cmd/watcher/main.go
results/config/101-mysql-deployment.yaml
results/config/api.yaml
results/test/e2e/README.md
results/test/e2e/install.sh
results/test/e2e/setup.sh
results/test/e2e/taskrun.yaml
results/test/e2e/test.sh

This adds e2e tests that test basic k8s deployment and resource
annotation. Tests use kind as the execution mechanism, but could also
theoretically be ran against any k8s cluster.
Also required the following changes for the e2e tests to pass:
- Disables Knative leader election.
- Sets real values in `config/` so that services can easily be brought
up.
- Configures mysql deployment to automatically create tables on startup.
This does not add the tests to the repo automation yet. When I tried to
run the presubmit_test.sh locally, the test hanged on the build tests.
This will require further investigation, so holding off for now.
review them: …

[results] Add e2e tests.

---

results/go.mod
results/pkg/api/server/db/errors.go
results/pkg/api/server/test/db.go
results/pkg/api/server/v1alpha1/server.go
results/pkg/api/server/v1alpha1/server_test.go
results/pkg/api/server/v1alpha2/result/result.go
results/pkg/api/server/v1alpha2/result/result_test.go
results/pkg/api/server/v1alpha2/results.go
results/pkg/api/server/v1alpha2/results_test.go
results/pkg/api/server/v1alpha2/server.go
results/pkg/watcher/reconciler/internal/test/clients.go
results/schema/results.sql

Implements the CreateResult and GetResult methods of the v1alpha2
interface.
Includes request validation, and some basic error handling.
Unfortunately since SQL error codes are somewhat impl specific, we will
need to do some additional work to fill out error handling (particularly
for MySQL). For now, focus on gorm/sqlite errors for unit testing.
review them:

[results] Implement v1alpha2 Create/GetResult.

---

cel/OWNERS

Creating a folder for incubating CELRun project which will provide a
Common Expression Language Custom Task, as proposed in https://github.com/tektoncd/community/issues/304
and adding the OWNERS to approve and review contributions to the project
review them:
/cc @bobcatfish @ImJasonH @pritidesai @afrittoli

[CELRun] Create cel folder and add OWNERS

---

task-loops/README.md
task-loops/pkg/apis/taskloop/v1alpha1/taskloop_types.go
task-loops/pkg/apis/taskloop/v1alpha1/zz_generated.deepcopy.go
task-loops/pkg/reconciler/tasklooprun/tasklooprun.go
task-loops/pkg/reconciler/tasklooprun/tasklooprun_test.go
task-loops/test/tasklooprun_test.go

Add support for TaskRuns to run in parallel.
A new field called concurrency is added to the TaskLoop CRD. It allows you to control the number of TaskRuns that can run in parallel. The default is 1.  If you specify 0 or a negative value, then the TaskRuns for all iterations are allowed to run concurrently.
review them:

Concurrency support for task looping

---

task-loops/tekton/publish.yaml
task-loops/tekton/release-pipeline.yaml

The image registry params has been split on imageRegistry +
imageRegistryPath. That allows for using imageRegistry in
the auth part and to align with pipeline builds.
review them:

[task-loops] Fix nightly release

---

commit-status-tracker/deploy/role.yaml

[commit-status-tracker] fix broken role.yaml - missing: taskruns. The Operator was not able to watch TaskRuns and was not running throwing an error. Added the missing resource.
review them:

[commit-status-tracker] Fix broken role.yaml - missing: taskruns

---

cel/tekton/README.md
cel/tekton/kustomization.yaml
cel/tekton/publish.yaml
cel/tekton/release-pipeline.yaml

Add the Tekton resources required for nightly builds of the
CEL. These are almost identical to those used by task-loops,
the main difference being that there is only one image,
the controller, to be built, no webhook.
review them:
/kind misc
/cc @jerop

[cel] Add nightly builds resources for CEL

---

pipelines-in-pipelines/tekton/README.md
pipelines-in-pipelines/tekton/kustomization.yaml
pipelines-in-pipelines/tekton/publish.yaml
pipelines-in-pipelines/tekton/release-pipeline.yaml

Add the Tekton resources required for nightly builds of the
pipelines in pipelines custom task. These are almost identical
to those used by task-loops, the main difference being that there
is only one image (controller) to be built, no webhook.
review them:
/cc @jerop

[pip] Add nightly builds resources for pip

---

task-loops/README.md
task-loops/pkg/reconciler/tasklooprun/tasklooprun.go
task-loops/pkg/reconciler/tasklooprun/tasklooprun_test.go

When the input parameter is dynamically generated, it is not
possible to produce a list. Add support for newline separated
list of items passed a single string.
This makes it possible for a task to produce a result that
is than used as iterate parameter in the task loop, and thus
to programmatically define the list of tasks to be executed.
review them:
/kind feature

[task-loops] Support string input for iterate parameter

---

pipelines-in-pipelines/pkg/reconciler/pip/piprun.go
pipelines-in-pipelines/pkg/reconciler/pip/piprun_test.go

In current implements, when create the new `pr`, its `OwnerReferences` is set to the original `pr`.
https://github.com/tektoncd/experimental/blob/ff79df0f529c229e85df93ae9cb1120d31c8455c/pipelines-in-pipelines/pkg/reconciler/pip/piprun.go#L198
The `Run`'s ownerRef, which means the original PR who created the Run.
But the `controller` will trigger by `pipelinerun informer` and with `Run` as it's `OwnerReferences`, see:
https://github.com/tektoncd/experimental/blob/ff79df0f529c229e85df93ae9cb1120d31c8455c/pipelines-in-pipelines/pkg/reconciler/pip/controller.go#L68-L71
In my case, my new created `pr` cost about 5m to complete, then the `Run`'s state keep as `unkonw` and original `pr` keep running forever. 
review …

[pipelines-in-pipelines]: the new created pr should has ownerref as the Run

---

pipelines-in-pipelines/README.md
pipelines-in-pipelines/examples/run-with-pipeline-with-results.yaml
pipelines-in-pipelines/pkg/reconciler/pip/piprun.go
pipelines-in-pipelines/pkg/reconciler/pip/piprun_test.go

This project provides `Custom Task` / `Runs` that execute `PipelineRuns`,
which enables users to configure `Pipelines` in `Pipelines`
This change propagates `PipelineResults` from the `PipelineRun` to the
`Run` that created it - it maps `PipelineResults` to `RunResult`
Propagating `Results` ensures that they can be reused in the `Run` and
in subsequent `Tasks` if configured as a `Pipeline` in a `Pipeline`
Closes https://github.com/tektoncd/experimental/issues/732
review them:

Pipelines in Pipelines: Propagate Results

---

cel/README.md

Users have been installing `ko` and using it to build and install the
controller on their clusters
We now have a Cron Job that builds a nightly release
https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/releases/cel-nightly
This change adds documentation for installing from the nightly release
/kind documentation
review them:

[cel] install from nightly release

---

cloudevents/go.mod
cloudevents/go.sum
cloudevents/pkg/reconciler/events/cloudevent/cloudevent.go
cloudevents/pkg/reconciler/events/cloudevent/cloudevent_test.go
cloudevents/pkg/reconciler/events/cloudevent/interface.go
cloudevents/pkg/reconciler/events/events.go
cloudevents/pkg/reconciler/events/events_test.go
cloudevents/pkg/reconciler/pipelinerun/reconciler_test.go

- extract reconciler/events/cloudevent library from tektoncd/pipeline to amke changes in the datatype which is being used in sending cloudevents
- replace existing TektonEventType based events with CDEEventType events
- Update TaskRun and PipelineRun to use Started and Finished events
- TaskRun and PipelineRun success/failure events don't exist yet so these have been replaced with cde "finished" events for time being
review them:

[cloudevents] use cde events for taskrun/pipelinerun start,finish

---

cloudevents/go.mod
cloudevents/go.sum
cloudevents/pkg/reconciler/events/cloudevent/artifacts.go
cloudevents/pkg/reconciler/events/cloudevent/artifacts_test.go
cloudevents/pkg/reconciler/events/cloudevent/cloudevent.go
cloudevents/pkg/reconciler/events/cloudevent/cloudevent_test.go
cloudevents/pkg/reconciler/events/cloudevent/interface.go
cloudevents/pkg/reconciler/events/cloudevent/interface_test.go
cloudevents/pkg/reconciler/events/cloudevent/results.go
cloudevents/pkg/reconciler/events/cloudevent/results_test.go
cloudevents/pkg/reconciler/pipelinerun/reconciler.go
cloudevents/pkg/reconciler/pipelinerun/reconciler_test.go

Add a new module that implements artifact event types, with the
corresponding selection logic.
WIP, still todo:
- function to build data
- change core logic to send all matching events
review them:

[cloudevents] Add support for handling artifact event types

---

cel/tekton/publish.yaml
pipelines-in-pipelines/tekton/publish.yaml
task-loops/tekton/publish.yaml
wait-task/tekton/publish.yaml

Before Tekton Pipelines v0.24.x, $HOME and workDir were implicitly set,
which rendered the cp command redundant and hid the issue.
Partially fixes tektoncd/plumbing#856
review them:

[cel][pip][wait][loop] Fix the cp command in the release publish task

---

notifiers/github-app/pkg/controller/controller.go
notifiers/github-app/pkg/controller/controller_test.go

Previously we would attempt to process the trigger, even if we didn't
find the information we needed, which would cause reconcile loops since
we'd report error. This changes the behavior to only process resources
that contain the GitHub annotations.
review them:
/kind bug

[github notifier] Short circuit if resources do not contain matching annotations.

---

cloudevents/pkg/reconciler/events/cloudevent/artifacts.go
cloudevents/pkg/reconciler/events/cloudevent/cloudevent.go
cloudevents/pkg/reconciler/events/cloudevent/services.go

Remove the resource name from the source and make sure it's set
always as subject. The resource name in the source makes it harder
to setup event filters / triggers based on source, so it should not
be included in there. That information is available in the subject
anyways already.
The group/kind/version information is missing in the objects passed
to "ReconcileKind", so for now do not use them to build the source.
The kind (PipelineRun vs. TaskRun) can be identified from the object
type, group is always tekton.dev for Tekton resources, and the version
store is also always v1beta1, so they don't add any interesting info
to the source anyways.
review …

[cloudevents] Fix source and subject

---

notifiers/github-app/pkg/controller/status.go
notifiers/github-app/pkg/controller/status_test.go

Certain statuses are failing with the error:
```
description is too long (maximum is 140 characters)
```
This truncates and descriptions to 140 characters if they exceed the
limit.
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)

[notifiers/github] Truncate GitHub status if > 140 chars

---

commit-status-tracker/README.md
commit-status-tracker/pkg/controller/pipelinerun/annotations.go
commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller.go
commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller_test.go

I added the possibility to provide the git-repo and git-revision as annotations.
This is should be useful when no git PipelineResource is used (e.g. git-clone Task) to fetch code from a repo.
review them:

[commit-status-tracker] git-repo and git-revision via annotations

---

notifiers/github-app/README.md
notifiers/github-app/pkg/controller/checkrun.go
notifiers/github-app/pkg/controller/checkrun_test.go
notifiers/github-app/pkg/controller/status.go
notifiers/github-app/pkg/controller/status_test.go

Adds an optional annotation to control what the statuses display name in
GitHub. If not specified, this defaults to the Task's name.
review them:
Fixes #779

[notifiers/github] Add display name annotation.

---

CONTRIBUTING.md

If projects are opened without the Owners file being merged first, then the top level owners of experimental repo have to review the whole project in the first pull request (which are usually big PRs as proof of concepts)
In this change, we recommend that contributors open an initial PR with the Owners file only so that the approvers of that specific project get permissions to approve the subsequent pull requests for that specific project 
This will remove the requirement that top level experimental maintainers, who may not be owners of the specific experimental project, have to review the whole project (and distributes the maintenance load from them)
Saw this scenario in https://github.com/tektoncd/experimental/pull/770#issuecomment-899700330
These are the criteria that every PR should …

Add details about adding Owners for new projects

---

pipeline-to-taskrun/OWNERS
pipeline-to-taskrun/README.md

I had tried to add the custom task and OWNERS file all at once in
https://github.com/tektoncd/experimental/pull/770 but @jerop pointed
out it's probably a better approach to just add the OWNERS file first,
which would allow getting the initial approval needed to kick off the
project and from then on the project OWNERS can take care of reviews
(and she documented this in
https://github.com/tektoncd/experimental/pull/782 !)
So this commit adds just the OWNERS (more welcome if anyone else is
interested!) for the pipeline to taskrun custom task, and there will be
a follow-up PR with the initial controller logic.
Project proposal: https://github.com/tektoncd/community/issues/447
review them: …

[pipeline-to-taskrun] Add initial directory for Pipeline to TaskRun custom task 🎁

---

test/presubmit-tests.sh

In #770 I tried to add the custom task and OWNERS file - with @jerop's
help I realized it would be easier to add the OWNERS file first so that
OWNERS can review the custom task itself - but even after that I was
still changing a file in the top level test dir to add the custom task
to the list of tests kicked off which needs top level OWNERS approval -
so this commit is doing that separately. Looking at the script it should
be safe to add a directory that doesn't exist because it should just get
ignored
review them: …

[pipeline-to-taskrun] Get ready to run presubmit tests 🏁

---

cel/config/500-controller.yaml
cloudevents/config/controller.yaml
pipeline-to-taskrun/config/500-controller.yaml
pipelines-in-pipelines/config/500-controller.yaml
task-loops/config/500-controller.yaml
task-loops/config/500-webhook.yaml
wait-task/config/controller.yaml

knative/pkg based controller and webhook need this environement
variable in order to not panic if metrics are enabled (through a
configmap).
This adds missing values for some of the project, and correct wrong
values for others.
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
Fixes #791 
/cc @afrittoli @jerop @bobcatfish @sbwsg @wlynch @dibyom @DrissiReda
review them:

Add or Update METRICS_DOMAIN to deployment 🍡

---

sdk/python/README.md

Fix the link to jupyter notebook containing examples for python sdk
/kind bug
review them:

[sdk/python] Fix the link to examples in sdk

---

task-loops/tekton/release-pipeline.yaml

The Task Loops nightlies have been failing for a while (most recent example
here:
https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns/task-loops-release-nightly-s4qzd?pipelineTask=unit-tests&step=unit-test)
The source of the errors appear to be an extra `-mod=vendor` param in the
`unit-tests` task and the `build` task executing from the root of the repo instead
of the task-loops subdirectory.
This commit fixes both of these issues and should hopefully repair the
task-loops nightlies.
review them:

[task-loops] Repair Task Loops Nightly Builds

---

pipeline-to-taskrun/tekton/publish.yaml
pipeline-to-taskrun/tekton/release-pipeline.yaml

Replace parameter expansion in build test Task workspace subpath with
hardcoded `pipeline-to-taskrun`
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
review them:

Modify pipeline-to-taskrun release pipeline

---

pipeline-to-taskrun/README.md
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/pipelinetotaskrun_test.go
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/steps.go
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/steps_test.go
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/taskrun.go
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/testdata/expected-taskrun.yaml
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/testdata/gcs-upload.yaml
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/testdata/git-clone.yaml
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/validate.go
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/workspaces.go
pipeline-to-taskrun/pkg/reconciler/pipelinetotaskrun/workspaces_test.go

Initially I left this out just to reduce the number of cases I needed to
cover but it was actually pretty easy to add. The functionality will be:
- When an optional workspace is provided, we do the same remapping we do
for other workspace
- When an optional workspace is not provided, we don't do any remapping
and just declare the same workspace as optional in the merged Task
I ran into this b/c I was trying to use pipeline to taskrun with the
latest git clone task in the catalog (0.4) which declares an optional
ssh-directory and I was frustrated that it didn't work.
review them:

[pipeline-to-taskrun] Support optional workspace ⚙️

---

cel/config/201-rolebinding.yaml
cel/config/202-clusterrolebinding.yaml
helm/dashboard/templates/clusterrolebinding.yaml
helm/pipeline/templates/clusterrolebinding.yaml
helm/triggers/templates/clusterrolebinding.yaml
pipelines-in-pipelines/config/201-rolebinding.yaml
pipelines-in-pipelines/config/202-clusterrolebinding.yaml
task-loops/config/201-rolebinding.yaml
task-loops/config/202-clusterrolebinding.yaml

The v1beta1 apiVersion will not be served in K8s v1.22 and above
See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122
review them:

Switch Cluster&RoleBindings apiVersion to v1

---

pipeline-in-pod/README.md
pipeline-in-pod/examples/inline-pipeline-inline-tasks.yaml
pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocated_pipelinerun_types_test.go
pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocated_pipelinerun_validation.go
pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocatedpipelinerun_types.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelineinpod.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pod.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/run.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/run_test.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/status.go
pipeline-in-pod/pkg/test/yaml_parsing.go

This commit adds support for Timeouts.Pipeline to the ColocatedPipelineRun custom task.
When the timeout is exceeded, the pod is deleted and the ColocatedPipelineRun is marked as failed.
review them:

[pipeline-in-pod] Timeouts.Pipeline support

---

pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
task-loops/pkg/reconciler/tasklooprun/tasklooprun_test.go
task-loops/test/tasklooprun_test.go

From
https://pkg.go.dev/github.com/google/go-cmp/cmp/cmpopts#IgnoreTypes:
IgnoreTypes returns an Option that ignores all values assignable to certain types,
which are specified by passing in a value of each type.
This means when we pass in apis.Condition{}.LastTransitionTime.Inner.Time,
we are actually ignoring all time.Time, not just that particular field.
Similarly for apis.Condition{}.Message, we are ignoring all strings.
This change uses IgnoreFields to correct the behavior. Luckily, this doesn't
impact the tests in a meaningful way.
See https://github.com/tektoncd/triggers/issues/1245 for issue where this was discovered.
/kind bug
review them:
- [n/a] Includes …

Use cmpopts.IgnoreFields instead of IgnoreType.

---

cel/tekton/README.md
cloudevents/tekton/README.md
pipeline-to-taskrun/tekton/README.md
pipelines-in-pipelines/tekton/README.md
tekton/README.md
tekton/customtask-release-pipeline.yaml
tekton/kustomization.yaml
tekton/publish-customtask.yaml

This commit moves the release pipeline and task that are copy-pasted in many places in experimental/
to a common location. Individual projects in experimental should be migrated to use this Pipeline and Task
with appropriate parameter values, instead of continuing to copy paste these definitions in multiple places.
This will be used first for the pipeline-in-pod project (the ColocatedPipelineRun custom task).
review them:
- n/a Commit messages includes a project tag in the subject - e.g. [OCI], [hub], [results], [task-loops]
Part 1 of #805

Create common release resources for custom tasks

---

test/presubmit-tests.sh

This commit adds presubmit tests for pipeline in a pod following instructions
in [contributing.md](https://github.com/tektoncd/experimental/blob/823989b2ceed7268d08c18e7d236a45f83f0d3a6/CONTRIBUTING.md#adding-a-new-project).
review them:

[Pipeline-in-pod] Add presubmit tests

---

pipeline-in-pod/config/201-clusterrole.yaml
pipeline-in-pod/config/202-clusterrolebinding.yaml

This ClusterRole and ClusterRole binding are the same as those applied to
the tekton pipelines controller. These are necessary for accessing service accounts
and creating workspace volumes.
review them:

[pipeline-in-pod] Add ClusterRole + Binding

---

pipeline-in-pod/config/300-colocatedpipelinerun.yaml

This commit updates the colocatedPipelineRun CRD to use apiextensions.k8s.io/v1.
review them:

[Pipeline-in-pod] Use customResourceDefinition v1

---

pipeline-in-pod/README.md
pipeline-in-pod/examples/inline-pipeline-inline-tasks.yaml
pipeline-in-pod/examples/inline-pipeline-taskrefs.yaml
pipeline-in-pod/examples/pipelineref.yaml
pipeline-in-pod/pkg/reconciler/pipelineinpod/apply.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/apply_test.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/entrypoint.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/entrypoint_test.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelineinpod.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/pod.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/status.go
pipeline-in-pod/pkg/reconciler/pipelineinpod/taskspec.go

This commit applies workspace volume mounts to each container in a Task
that declares that workspace. This allows tasks to share data
in a workspace.
It also adds support for default parameters and replacing result paths.
review them:

[Pipeline-in-pod] Apply workspace volume mounts

---

pipeline/trusted-resources/pkg/trustedtask/trustedpipeline_test.go
pipeline/trusted-resources/pkg/trustedtask/trustedpipelinerun_test.go
pipeline/trusted-resources/pkg/trustedtask/trustedtask_test.go
pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go

Refactor the helper func `getSignerFromFile` to remove the unused `error` return val
review them:

[pipeline/trusted-resources] Refact/clean error on return vals

---

task-loops/test/tasklooprun_test.go

This test is broken and blocking PRs in other experimental projects from being submitted. Tekton has chosen to deprecate ClusterTasks, and the TaskLoop functionality has now been implemented by Matrix, so it's not clear that we are getting much value from this test right now.
review them:

[Task-loops] Remove ClusterTask tests

---

concurrency/OWNERS
concurrency/README.md

This commit adds a new directory and OWNERS file for an experimental project to address TEP-0120 (Canceling concurrent PipelineRuns).
review them:

[Concurrency] New project

---

concurrency/README.md
concurrency/cmd/webhook/main.go
concurrency/config/500-webhook-configuration.yaml
concurrency/examples/concurrencycontrol.yaml
concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types.go
concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types_test.go
concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go

This commit adds support for all three PipelineRun cancelation strategies to ConcurrencyControls. There is currently no default strategy. If multiple strategies could apply to a PipelineRun, concurrency controls will fail.
review them:

[concurrency] Support multiple cancelation strategies

---

concurrency/cmd/webhook/main.go
concurrency/config/500-webhook-configuration.yaml

With two separate mutating admission webhooks (one for concurrencycontrol defaults and one for patching pipelineruns as pending), one seems to be ignored. This commit merges them into a single mutating admission webhook that applies both sets of configurations.
review them:

[concurrency] Merge mutating admission webhooks

---

concurrency/README.md
concurrency/cmd/webhook/main.go
concurrency/config/201-clusterrole.yaml
concurrency/config/concurrency-config.yaml
concurrency/pkg/apis/config/config.go
concurrency/pkg/apis/config/config_test.go
concurrency/pkg/apis/config/testdata/concurrency-config-all-namespaces.yaml
concurrency/pkg/apis/config/testdata/concurrency-config-multiple-namespaces.yaml
concurrency/pkg/apis/config/testdata/concurrency-config-one-namespace.yaml
concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go
concurrency/pkg/reconciler/concurrency/controller.go

This commit adds the ability to configure the behavior of the concurrency controller and webhook via a new configmap "concurrency-config" in the "tekton-concurrency" namespace. It allows the user to specify a list of namespaces where the concurrency controller and webhook should be allowed to modify PipelineRuns, and defaults to all namespaces.
Alternatively, a NamespaceSelector could be applied to the MutatingAdmissionWebhook that patches PipelineRuns as pending. However, this would not prevent the concurrency controller from operating on PipelineRuns in other namespaces.
/cc @afrittoli 
review them:
for more …

[concurrency] Add namespace allowlist

---

concurrency/examples/concurrencycontrol.yaml
concurrency/examples/pipelinerun.yaml
concurrency/go.mod
concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types.go
concurrency/pkg/apis/concurrency/v1alpha1/zz_generated.deepcopy.go
concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go

This commit adds a new "groupBy" field to concurrencyControl, allowing grouping by multiple label keys. PipelineRuns with all the same matching values for these label keys are part of the same concurrency group.
review them:

[concurrency] Add functionality to group by labels

---

workflows/config/201-clusterrole.yaml
workflows/examples/build-on-branch-change.yaml
workflows/examples/github-ci-workflow.yaml
workflows/pkg/convert/convert_test.go
workflows/pkg/filters/filters.go
workflows/pkg/filters/filters_test.go
workflows/pkg/reconciler/workflows/workflows.go

This commit contains the following bug fixes:
- Allows the workflows controller to correctly update triggers, by ensuring
the controller sets a resource version by deepcopying the existing trigger before updating it.
- Allows the workflows controller to publish events
- Fixes CEL syntax for gitref filter
- Updates syntax of examples to work correctly
review them:

[workflows] Misc bug fixes

---

concurrency/cmd/webhook/main.go
concurrency/config/500-webhook-configuration.yaml
concurrency/go.mod
concurrency/pkg/mutatingwebhook/mutatingwebhook.go

This commit writes a new mutating admission webhook to patch PipelineRuns as pending. This addresses two bugs:
1. The existing mutating webhook calls PipelineRun.SetDefaults, which is the responsibility of the PipelineRun admission webhook rather than the concurrency admission webhook. If the version of Pipelines installed on the cluster differs from the version used in the concurrency webhook, this could cause bugs.
2. A resource's namespace isn't always available in the unstructured object provided by knative's defaulting admission controller. This commit rewrites the admission webhook to have access to the entire AdmissionRequest, which has the namespace populated.
review them:
- n/a Includes …

[concurrency] Move PipelineRun mutation into separate webhook

---

pipelines-in-pipelines/pkg/reconciler/pip/piprun.go

The Pipelines-in-Pipelines is provided by a controller that implements the Custom Task interface. Currently, the timeout cannot be specified for the pipelines-in-pipelines tasks so it can only inherit the default timeout, which may cause child pipelineRuns to fail when a different timeout is required. In addition, the podTemplate cannot be set either when triggering the child pipelineRun so it may also fail when a podTemplate is required to run the child pipelineRun.
This PR addresses the above issues, by setting Timeout for the pipelineRun from customRun's spec, and inheriting the podTemplate from the owner pipelineRun.
review them: …

[pipelines-in-pipelines] Support timeout and pod template for pipelines-in-pipelines

---

pipelines-in-pipelines/pkg/reconciler/pip/piprun.go
pipelines-in-pipelines/pkg/reconciler/pip/piprun_test.go

The Pipelines-in-Pipelines is provided by a controller that implements the Custom Task interface. Currently, the cancellation is not implemented for the customRun so when the main pipelineRun is cancelled, the pipelineRuns spawned by the customRuns won't be cancelled accordingly, which can lead to confusion.
This PR addresses the above issue, by cancelling the spawned pipelineRuns when the corresponding customRuns are marked as Cancelled.
review them:

[pipelines-in-pipelines] Support cancellation for pipelines-in-pipelines
